### ISSUE TITLE
Trouble upgrading to react-native 0.3.10

### ISSUE THREAD

**Issue by VonD** [corymsmith/react-native-icons#10]
Hi,

After upgrading react-native to 0.3.10 (from 0.3.4) the project build fails with the following : Did you forget to use RCT_EXPORT_MODULE() ? (see attachments). Downgrading back to 0.3.4 solves the issue.

Thank you.

![capture d ecran 2015-04-09 a 18 57 56](https://cloud.githubusercontent.com/assets/752330/7072264/3953f5fe-deeb-11e4-84b0-a2b069b85557.png)
![capture d ecran 2015-04-09 a 18 40 59](https://cloud.githubusercontent.com/assets/752330/7072265/395714f0-deeb-11e4-8aed-53e593746357.png)

**Comment by corymsmith** [comment]
Thanks for letting me know, I'll have to test that out as well!

**Comment by VonD** [comment]
just in case : https://github.com/facebook/react-native/issues/793

**Comment by mikkoj** [comment]
Adding RCT_EXPORT_MODULE() to all Manager-implementations in ReactNativeIcons-project made 0.3.10 work for me.

**Comment by dmnkgrc** [comment]
@mikkoj worked for me too.

**Comment by corymsmith** [comment]
I'll fix this today, thanks everyone!

**Comment by corymsmith** [comment]
Fixed and pushed to NPM as version 0.0.2
