### ISSUE TITLE
Integration with ToolbarAndroid

### ISSUE THREAD

**Issue by Mokto** [corymsmith/react-native-icons#102]
Hi guys,

I don't even know if it is possible but it would really nice if icons could be integrated as navIcon or as actions icons in [ToolbarAndroid](https://facebook.github.io/react-native/docs/toolbarandroid.html#props)

navIcon should be an Image (Image.propTypes.source)

Am I crazy ? :+1:

**Comment by corymsmith** [comment]
I'm just publishing a version with Android support at the moment, the only way to get the action icons into the Toolbar would be to write a custom implementation like I had to do for TabBarIOS.

**Comment by Mokto** [comment]
Ok I might do it soon.

;)

**Comment by corymsmith** [comment]
Going to close this as I think its best to just create a custom Toolbar or a separate component that handles this,.
