### ISSUE TITLE
Compatibility between IOS and Android

### ISSUE THREAD

**Issue by Mokto** [corymsmith/react-native-icons#105]
Hi guys,

Currently icons are written in camelCase for iOS (ie __fullscreenExit) but it is not the same writing in android (ie fullscreen-exit).

Is it what you want ?

**Comment by corymsmith** [comment]
The method name is camelcase in iOS but you would still use fontname|fullscreen-exit as I convert it to find the icon

**Comment by Mokto** [comment]
Oh I'm sorry I did not understand that !

Thank you.
