### ISSUE TITLE
Some strange errors on SMXTabBar.m when compiling

### ISSUE THREAD

**Issue by pedramsaleh** [corymsmith/react-native-icons#107]
The errors are:

`<project path>/node_modules/react-native-icons/ios/ReactNativeIcons/IconTabBarItem/SMXTabBar.m:80:9: No visible @interface for 'SMXTabBar' declares the selector 'reactAddControllerToClosestParent:'`

and 

`<project path>/node_modules/react-native-icons/ios/ReactNativeIcons/IconTabBarItem/SMXTabBar.m:86:42: Property 'reactViewController' not found on object of type 'SMXTabBarItem *'; did you mean 'inputViewController'?`

Any idea why these might be happening?  Not sure what I did to cause these, but I was uninstalling and re-installing other packages for the same project and ran into this, so I uninstalled and re-installed react-native-icons but this error still occurs when compilint.  I'm using 0.4.0 BTW.

**Comment by corymsmith** [comment]
What version of react native are you using?

**Comment by pedramsaleh** [comment]
0.8.0.  Was working fine with that version until recently.

**Comment by pedramsaleh** [comment]
Here's a screenshot of where the error is happening.

![capture](https://cloud.githubusercontent.com/assets/12803855/10321063/b271deb0-6c44-11e5-948a-3c54f7e43a11.PNG)

**Comment by corymsmith** [comment]
@pedramsaleh You'll have to upgrade React Native or use an older version of this library (0.3.3)

**Comment by pedramsaleh** [comment]
Oh, I thought 0.4.0 was OK for older versions of RN (according to the installation instructions).  OK, I'll give that a shot.

**Comment by pedramsaleh** [comment]
Worked, thanks.
