### ISSUE TITLE
Project flow for teams

### ISSUE THREAD

**Issue by morenoh149** [corymsmith/react-native-icons#109]
I'm working on a team and we decided to try this project. Does every member of the team need to repeat the installation process? The team member that first added this did notice changes in the `ios` directory and added them to git version control. But the project doesn't seem to work on machines that did not perform those steps.

**Comment by morenoh149** [comment]
Ah, looks like if you open the project in xcode and trigger a rebuild then the new assets are picked up properly. Perhaps a note in the readme is warranted?

**Comment by MossP** [comment]
Surely this is an issue for your source management? Generally node_modules is gitIgnored so every user would need to install it, that's why you have a dependencies file to keep everyone up to date without the need to share specifics of each machine setup. Maybe I've missed something?

**Comment by morenoh149** [comment]
yep. It was something else. Sorry.

**Comment by MossP** [comment]
Ah, No probs. Glad that you got it working :)
