### ISSUE TITLE
Installation: Followed all steps Build Error 

### ISSUE THREAD

**Issue by hookercookerman** [corymsmith/react-native-icons#11]
so I have done 1-6 steps all good; 

just checking that its not me doing something dumb:

I get duplicate symbols for architecture x86_64

cheers 

React Version 0.3.11

**Comment by corymsmith** [comment]
Which symbols are duplicates?

**Comment by hookercookerman** [comment]
45;

_OBJC_CLASS_$_FAKIcon
_OBJC_METACLASS_$_FAKIcon
_OBJC_IVAR_$_FAKIcon._mutableAttributedString

etc

**Comment by corymsmith** [comment]
It seems like those classes are getting included multiple times for some
reason, haven't seen this error with this module myself.

Thanks,

Cory Smith
http://ca.linkedin.com/in/corysmith/
http:/twitter.com/smixx http://twitter.com/smixx

**Comment by hookercookerman** [comment]
ok cool have tried clean builds; still no good; same error

but I will give this another go will close

 cheers for help
