### ISSUE TITLE
[Android] `IconImage` has no propType for native prop 'SMXIconImage.scaleX' of native type `number`

### ISSUE THREAD

**Issue by timzaak** [corymsmith/react-native-icons#111]
with the react-native of latest master branch

**Comment by corymsmith** [comment]
@timzaak Are you still having this issue? This looks the same as: https://github.com/facebook/react-native/issues/1812

**Comment by timzaak** [comment]
I test it with the lastest source, the problem still happens. Just waiting for the rect-native 0.13.0 version releases,  and then try to solve this problem. I close this issue now.

**Comment by lalith26** [comment]
I am facing the same in v0.13.2 as well

**Comment by corymsmith** [comment]
What version of this library are you using?
