### ISSUE TITLE
IOS build failed

### ISSUE THREAD

**Issue by pengkobe** [corymsmith/react-native-icons#113]
I had exactly done what the author told to~
but it just show out:
MyAPP/node_modules/react-native-icons/ios/ReactNativeIcons/IconTabBarItem/SMXTabBar.m:88:56: No visible @interface for 'RCTWrapperViewController' declares the selector 'initWithContentView:'

**Comment by pengkobe** [comment]
sorry to bother, I miss this:
If you need to support React Native version < 0.12.0-rc use:
npm install react-native-icons@0.4.0 --save
:)

**Comment by corymsmith** [comment]
No worries!
