### ISSUE TITLE
Octicons support 

### ISSUE THREAD

**Issue by skyline75489** [corymsmith/react-native-icons#114]
The upstream repo [FontAwesomeKit](https://github.com/PrideChung/FontAwesomeKit) has added support for Octicons. I think it't would be too hard to add it here, right?

**Comment by corymsmith** [comment]
I have it mostly implemented for Android but will have to write some custom code for iOS as well! Will probably include it in the next release

**Comment by skyline75489** [comment]
Great! I'm looking forward to it.

**Comment by corymsmith** [comment]
Just added this and published to NPM in v0.6.3
