### ISSUE TITLE
Using Animated with icons

### ISSUE THREAD

**Issue by tgoldenberg** [corymsmith/react-native-icons#115]
So I was checking out the Animated features on the React Native site - [example](https://facebook.github.io/react-native/docs/animations.html). I am able to get the bounce feature working for an Animated.Image component, but when I apply the same styles to the React Native icon I get the error - `Invariant Error: Transform with key of "scale" must be a number: {"scale": {"_children": [], "_value": "0.8", "_offset": 0, "_animation": "null", "_listeners": {}}}` 

Any suggestions? Thanks!

**Comment by corymsmith** [comment]
@tgoldenberg Can you post some sample code of what you were trying to do?

**Comment by tgoldenberg** [comment]
@corymsmith I got it working with the `<Animated.View/>` component wrapping around the icon. Thanks for the support, though!

**Comment by corymsmith** [comment]
Perfect, that was going to be my suggestion :)

**Comment by digitalmaster** [comment]
**Facepalm** just made the same mistake

**Comment by corymsmith** [comment]
You should really be using react-native-vector-icons instead
