### ISSUE TITLE
Setting the color for icons using style in Android works but it does not work in iOS

### ISSUE THREAD

**Issue by drager** [corymsmith/react-native-icons#117]
Hey!

Setting the color for the icons using the style attribute in Android works but it does not work in iOS.

Code below:

```
const layoutStyles = Object.freeze({
  icon: Object.assign({
      width: 32,
      height: 32,
  }, color: 'rgba(0, 0, 0, 0.54)'),
});
```

When doing the following in Android:

```
<Icon
   name={this.props.icon}
   size={layoutStyles.icon.width}
   style={layoutStyles.icon}
/>
```

The color will be same as I choose for the style attribute. But doing that does not work in iOS so I need to apply the color attribute as well which results in the following code:

```
<Icon
   name={this.props.icon}
   size={layoutStyles.icon.width}
   style={layoutStyles.icon}
   color={layoutStyles.icon.color}
/>
```

So the style attribute does not apply the color in iOS.

Which is the desired behaviour? Is Android wrong or is iOS? I prefer the Android way to be honest.

Thanks.

**Comment by corymsmith** [comment]
I haven't updated the iOS code to support that yet. I added that when I implemented Android support. Hoping to include it in the next release

**Comment by drager** [comment]
Great! Thanks.

**Comment by corymsmith** [comment]
Closing this as support for this library is being discontinued, I highly recommend using https://github.com/oblador/react-native-vector-icons instead as its more fully featured, I've added a warning to the Readme about this as well.
