### ISSUE TITLE
Icon not visible on Android

### ISSUE THREAD

**Issue by mangogogos** [corymsmith/react-native-icons#119]
Just started up a new project to test this project out but Im getting a blank screen with the following relevant code
# index.android.js:

'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} = React;

var { Icon, } = require('react-native-icons');

var blah = React.createClass({
  render: function() {
    return (
      <View style={styles.container}>
        <Icon
          name='ion|beer'
          size={50}
          color='#050505'
          style={{ width: 50, height: 50, margin: 5, color: '#050505' }}
        />
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
});

AppRegistry.registerComponent('blah', () => blah);
# settings.gradle:

rootProject.name = 'blah'

include ':app'
include ':react-native-icons'
project(':react-native-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-icons/android')
# build.gradle:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

```
defaultConfig {
    applicationId "com.blah"
    minSdkVersion 16
    targetSdkVersion 22
    versionCode 1
    versionName "1.0"
    ndk {
        abiFilters "armeabi-v7a", "x86"
    }
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:0.12.+'
    compile project(':react-native-icons')
}
# and MainActivity.java:

package com.teampages_mobile;

import android.app.Activity;
import android.os.Bundle;
import android.view.KeyEvent;

import com.facebook.react.LifecycleState;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactRootView;
import com.facebook.react.modules.core.DefaultHardwareBackBtnHandler;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import com.smixx.reactnativeicons.ReactNativeIcons;

public class MainActivity extends Activity implements DefaultHardwareBackBtnHandler {

```
private ReactInstanceManager mReactInstanceManager;
private ReactRootView mReactRootView;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    mReactRootView = new ReactRootView(this);

    mReactInstanceManager = ReactInstanceManager.builder()
            .setApplication(getApplication())
            .setBundleAssetName("index.android.bundle")
            .setJSMainModuleName("index.android")
            .addPackage(new MainReactPackage())
            .addPackage(new ReactNativeIcons())
            .setUseDeveloperSupport(BuildConfig.DEBUG)
            .setInitialLifecycleState(LifecycleState.RESUMED)
            .build();

    mReactRootView.startReactApplication(mReactInstanceManager, "blah", null);

    setContentView(mReactRootView);
}

@Override
public boolean onKeyUp(int keyCode, KeyEvent event) {
    if (keyCode == KeyEvent.KEYCODE_MENU && mReactInstanceManager != null) {
        mReactInstanceManager.showDevOptionsDialog();
        return true;
    }
    return super.onKeyUp(keyCode, event);
}

@Override
public void onBackPressed() {
  if (mReactInstanceManager != null) {
    mReactInstanceManager.onBackPressed();
  } else {
    super.onBackPressed();
  }
}

@Override
public void invokeDefaultOnBackPressed() {
  super.onBackPressed();
}

@Override
protected void onPause() {
    super.onPause();

    if (mReactInstanceManager != null) {
        mReactInstanceManager.onPause();
    }
}

@Override
protected void onResume() {
    super.onResume();

    if (mReactInstanceManager != null) {
        mReactInstanceManager.onResume(this);
    }
}
```

}

**Comment by aeperea** [comment]
+1

**Comment by therealcisse** [comment]
+1

**Comment by corymsmith** [comment]
Can a few more of you post a Gist of what you have so I can look into it?

**Comment by alexkrolick** [comment]
```
'use strict';

var React = require('react-native');
var {Icon} = require('react-native-icons');

var {
  StyleSheet,
  Text,
  View,
  TextInput,
} = React;

var MyClass = React.createClass({
  render() {
    return(
      <View>
        <Text>Icons Go Here</Text>
        <Icon
          name='fontawesome|map'
          size={70}
          color='#ffffff'
          style={styles.icon}
        />
      </View>
    );
  },
});

var styles = StyleSheet.create({
  icon: {
    backgroundColor: '#3b5998',
    color: '#ffffff',
    width: 70,
    height: 70,
  },
});
```

I'm getting a blue square where the icon goes, with nothing on it.

The app also crashes when clicking in the square.

**Comment by alexkrolick** [comment]
Update: I had the icon sets + json in a subfolder of android/.../assets, where they couldn't be found. App no longer crashes.

**Comment by corymsmith** [comment]
Perfect, do it's working?

**Comment by alexkrolick** [comment]
Yes, it is working. Can't speak for the others.

**Comment by mangogogos** [comment]
Yeah I also had an issue with my icon sets. Im closing the issue thanks @corymsmith and @whokilledtheelectricmonk
