### ISSUE TITLE
Error when pushing to app store

### ISSUE THREAD

**Issue by JimmyMow** [corymsmith/react-native-icons#121]
Hey Cory. Everything is working perfectly in the simulator and when I load my app on my device and my friends devices. But when I submitted to the app store I got this error: 

"Invalid Bundle Structure - The binary file 'sports.app/FAKFontAwesome.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect."

**Comment by Mokto** [comment]
Hi !

You have to remove FAKFontAwesome.o from Build Phases / Copy Bundle Resources.

Please let me know if something is still not working.

**Comment by JimmyMow** [comment]
Hello!

Thanks for your help. I started looking for a FAKFontAwesome.o file when I got the error, but I couldn't find one. The only FAKFontAwesome files in my Build Phases / Copy Bundle Resources are:

FAKFontAwesome.h
FAKFontAwesome.m

I have a FontAwesome.otf that I tried removing but that breaks the app, and the other file I have is FontAwesomeKit.h

**Comment by corymsmith** [comment]
@JimmyMow Did you get this working? If not this may be the reason: http://onebigfunction.com/ios/2015/03/15/invalid-bundle-structure/

Can you post a screenshot of both your Copy Bundle Resources and Build Phases?

**Comment by dorthwein** [comment]
So the solution for me was in the build phases/ copy bunder resources you remove all the FAKFontAwesome.m & FAKFontAwesome.h files but leave the font files.  You need to do this for all the FAK Related fonts/icons etc....

**Comment by corymsmith** [comment]
That's correct, the .m and .h files should never be included under Copy Bundle Resources

**Comment by corymsmith** [comment]
Going to close this as I'm sure thats the issue.
