### ISSUE TITLE
No Icon font named '(null)'

### ISSUE THREAD

**Issue by jneumann** [corymsmith/react-native-icons#122]
When I run the example project included with the repository everything works fine, but when I try to use the library with my own projects, I keep getting No Icon font named '(null)'. I believe that it is an issue with how the font files are being loaded, but I can't be 100% sure on that.
<img width="487" alt="screen shot 2015-10-21 at 9 00 30 am" src="https://cloud.githubusercontent.com/assets/4145595/10639039/a2f48d76-77d3-11e5-865d-f01d3ff831a6.png">

**Comment by corymsmith** [comment]
Can you post the code you're trying to use? I think its an issue with how
its being declared.

Thanks,

Cory Smith
http://ca.linkedin.com/in/corysmith/
http:/twitter.com/smixx http://twitter.com/smixx

**Comment by jneumann** [comment]
https://gist.github.com/jneumann/f9c483b9fccc4d9dd44e

**Comment by corymsmith** [comment]
You're missing:

iconName={'ion|ios-paper-outline'}
iconSize={32}

You can also specify the following if the icon is different when selected
vs. just being tinted a different color:

selectedIconName={'ion|ios-paper'}

Thanks,

Cory Smith
http://ca.linkedin.com/in/corysmith/
http:/twitter.com/smixx http://twitter.com/smixx

**Comment by corymsmith** [comment]
@jneumann any luck?

**Comment by jneumann** [comment]
That fixed it for me, thank you for your help!
