### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Pajn** [corymsmith/react-native-icons#125]
Would be great if you published a new release so we get the support for 0.13

**Comment by vincentfretin** [comment]
In the mean time, you can use in your package.json:
"react-native-icons": "corymsmith/react-native-icons",

**Comment by corymsmith** [comment]
Will do this today

**Comment by corymsmith** [comment]
@Pajn @vincentfretin I just published 0.6.0 to NPM with support for RN 0.13 and 0.14.0-rc
