### ISSUE TITLE
libReactNativeIcons.a file appears red in Xcode, file not being downloaded

### ISSUE THREAD

**Issue by jonolock91** [corymsmith/react-native-icons#126]
Even if I download the react-native-icons package via npm or via the zip file option, whenever I add the xcodeproj file under my Xcode libraries folder the libReactNativeIcons.a file appears red, indicating that it is missing. I have tried re-installing, updating the node package but with no success, any ideas please?

**Comment by corymsmith** [comment]
It should still build when you build

**Comment by jonolock91** [comment]
Just tried adding libReactNativeIcons.a to my Link binary with libraries, and it does build, I didn't think it did sorry. How would I add the icons to my Copy build resources now, my app crashes once it loads any page which has an icon on (which is expected). When I add the icon font files to Copy build resources, which option should I choose: 'Copy items if needed', 'Create groups', 'Create folder references'. I left it as default before and I think this was the stage where it just wouldn't build anymore.

**Comment by corymsmith** [comment]
@jonolock91 Don't choose any of those options when adding the font files and it should work.

**Comment by jonolock91** [comment]
It seems like I have to select one of those options <img width="1280" alt="screen shot 2015-10-27 at 17 38 18 copy" src="https://cloud.githubusercontent.com/assets/11156990/10767013/0dee20a8-7cd2-11e5-9005-f6e58b09db5d.png">

**Comment by corymsmith** [comment]
@jonolock91 What are you selecting? A folder or the individual files?

**Comment by jonolock91** [comment]
Under 'Copy bundle resources' I press the +, 'Add other...', Find the node module, under ReactNativeIcons libraries FontAwesomeKit, I choose: FontAwsome.otf and ionIcons.ttf

**Comment by corymsmith** [comment]
@jonolock91 Since you're not adding a folder that option doesn't apply so you just stuck with the default "Create Groups"

**Comment by corymsmith** [comment]
@jonolock91 Any luck?

**Comment by jonolock91** [comment]
That worked thanks :) I can't understand why it didn't work before now, what I did differently, but thank you for your time!

**Comment by corymsmith** [comment]
Great to hear!
