### ISSUE TITLE
icon name with space

### ISSUE THREAD

**Issue by morenoh149** [corymsmith/react-native-icons#127]
How can I use https://www.google.com/design/icons/#ic_swap_horiz ? I'm pretty sure I have the material font as the `face` icon works. But how do I specify `swap horiz`?

**Comment by corymsmith** [comment]
I'm using this icon font at the moment which doesn't have some of the newer / updated icons or they may be named a bit differently. In your case you can use `swap`  which looks to be the same as `swap horiz`

**Comment by morenoh149** [comment]
ah so it's just a matter of updating the included font version? would be helpful to also demonstrate using a font with a space in the name just for other's sanity. I'll let you decide what's best. Tag @kahdojay

**Comment by zavoloklom** [comment]
@morenoh149, @corymsmith,
Name of this icon in MDIF is `swap`, you can find it in [Directional Section](http://zavoloklom.github.io/material-design-iconic-font/icons.html#directional)

**Comment by morenoh149** [comment]
ah so I was using the wrong site for the icon names as well. Good to know.
