### ISSUE TITLE
ToolbarAndroid support?

### ISSUE THREAD

**Issue by jonolock91** [corymsmith/react-native-icons#129]
Hi, I see that you said there currently isn't support for 'Tab Bar' on Android, is this the ToolbarAndroid component? If so, when do you think this could be possible to implement, as using images for the Toolbar seems like a long winded way of displaying icons.

**Comment by corymsmith** [comment]
Hey Jonathan,

The tab bar mentioned there is referring to the iOS style standard bottom tab bar. I don't have any plans to add ToolbarAndroid support but always open to PR's for that type of thing.
