### ISSUE TITLE
'User Search Paths' not in Xcode

### ISSUE THREAD

**Issue by adriansdev** [corymsmith/react-native-icons#13]
I'm stuck on point 6. There are a number of similar labels in Build Settings but none which are exactly 'User Search Paths'. The photo shows my available option

![search paths](https://cloud.githubusercontent.com/assets/5958031/7165423/8fa8bde6-e39f-11e4-93e5-6d088f0f4461.png)

**Comment by corymsmith** [comment]
That's my bad, it's the User Header Search Paths option

**Comment by corymsmith** [comment]
@adrian-social-prod Did you end up getting this working?

**Comment by adriansdev** [comment]
Hi, not quite, I have the 'No manager class found for view with module name "FAKIconImage"' problem, which i can't figure out. 

When I set User Header Search Paths only the Debug field is populated but Release does show the path when i click on it and they are set to recursive.

Thanks

![search paths](https://cloud.githubusercontent.com/assets/5958031/7176221/4eb76e84-e414-11e4-98e9-ff657ebee5b2.png)

I think your example on the front page is missing the Icon require line
var Icon = require('FAKIconImage');

**Comment by corymsmith** [comment]
Did you add the .a file? This is usually when the static lib isn't included.

**Comment by josebalius** [comment]
@corymsmith I am not seeing User Header Search Paths in the ReactNativeIcons Project Build Settings......what I'm I missing?

**Comment by corymsmith** [comment]
@josebalius You should see it if you click on the ReactNativeIcons target and then go to the build settings.

![screenshot 2015-04-17 15 12 28](https://cloud.githubusercontent.com/assets/7315/7211012/f32397fe-e513-11e4-9fce-bf4482bf9802.png)

**Comment by josebalius** [comment]
@corymsmith thank you! I had `Basic` selected instead of `All` <--- ios newb. Now the project won't build, but i'll continue to debug that and report back.

**Comment by corymsmith** [comment]
Ok let me know, glad to help!
