### ISSUE TITLE
Material Design icons

### ISSUE THREAD

**Issue by zavoloklom** [corymsmith/react-native-icons#131]
Hello!
If you use my font for MD icons, maybe it can be useful to give a link to a [Icons Set](http://zavoloklom.github.io/material-design-iconic-font/icons.html) or [Cheatsheet](http://zavoloklom.github.io/material-design-iconic-font/cheatsheet.html)?
Starting with MD Iconic Font version 2.1 icons names may be very different from the original and it can confuse people.

**Comment by corymsmith** [comment]
That's a great idea Sergey, was thinking the same thing

**Comment by corymsmith** [comment]
Added!

**Comment by zavoloklom** [comment]
@corymsmith, thank you!
