### ISSUE TITLE
React Native 0.15.0-rc: Error - Incompatible block types

### ISSUE THREAD

**Issue by patelsan** [corymsmith/react-native-icons#132]
I am getting following error after upgrading RN to 0.15.0-rc, any suggestions?

`.../node_modules/react-native-icons/ios/ReactNativeIcons/IconTabBarItem/SMXTabBar.m:97:52: Incompatible block pointer types sending 'void (^)(SMXTabBarItem *__strong, NSUInteger, BOOL *)' to parameter of type 'void (^ _Nonnull)(UIView<RCTComponent> * _Nonnull __strong, NSUInteger, BOOL * _Nonnull)'`

**Comment by corymsmith** [comment]
I haven't tested out 0.15.0-rc so may be a breaking change that we'll have to fix

**Comment by patelsan** [comment]
I wish I knew more Objective C to help out with this. Switching to 0.14 for now. Closing the issue as RN version is still RC. Thanks for this great work!

**Comment by corymsmith** [comment]
I believe that #133 fixes this

**Comment by patelsan** [comment]
Great. Thanks.

**Comment by corymsmith** [comment]
Just published 0.6.2 to NPM and it includes this PR

**Comment by ibrens** [comment]
Just came across this with RN 0.16.0, upgraded and it works fine
