### ISSUE TITLE
Tab Bar Icons will not display

### ISSUE THREAD

**Issue by jaysig** [corymsmith/react-native-icons#135]
I'm trying to get the ion icons to display like in the demo; however, i'm unable to get any of them to show up. I am only able to use the system icons and the base64 icon on the React Native site. 

I have var { TabBarIOS, } = require('react-native-icons'); at the top. 

Calling it this way.

```
render() {
    return (
      <TabBarIOS selectedTab={this.state.selectedTab}
      tintColor={'#c1d82f'}
      barTintColor={'#000000'}
      >
      <TabBarIOS.Item
      name="todos"
      title='todos'
      iconName={'ion|chatboxes'}
      selected={this.state.selectedTab === 'todos'}
      onPress={() => {
        this.setState({
          selectedTab: 'todos',
        });
      }}>
      <Todos />
      </TabBarIOS.Item>
```

Here is how my library looks 
![screenshot 2015-11-12 15 19 24](https://cloud.githubusercontent.com/assets/4924440/11130029/d966419a-8950-11e5-964e-1f82f690d8a3.png)

Link Binary
![screenshot 2015-11-12 15 40 19](https://cloud.githubusercontent.com/assets/4924440/11130621/00889982-8954-11e5-90d7-77d4342f41c9.png)

 my build phases. 
![screenshot 2015-11-12 15 19 13](https://cloud.githubusercontent.com/assets/4924440/11130035/de8ff94a-8950-11e5-8127-9047f7f57021.png)

Any suggestions?

**Comment by corymsmith** [comment]
Try adding an iconSize property to each tab bar item.

**Comment by corymsmith** [comment]
I should probably add some warnings for things like this so it's obvious what the issue is

**Comment by jaysig** [comment]
Just updated it to this 

```
  <TabBarIOS selectedTab={this.state.selectedTab}
      tintColor={'#c1d82f'}
      barTintColor={'#000000'}
      >
      <TabBarIOS.Item
      name="todos"
      iconName={'ion|ios-home-outline'}
      selectedIconName={'ion|ios-home'}
      title={''}
      iconSize={32}
      selected={this.state.selectedTab === 'todos'}
      onPress={() => {
        this.setState({
          selectedTab: 'todos',
        });
      }}>
      <Todos />
      </TabBarIOS.Item>
```

still not displaying anything or throwing errors

**Comment by corymsmith** [comment]
Can you share your require statements, just wondering if you're using the react native tabbar / item or the one included in this library.

**Comment by jaysig** [comment]
```
var React = require('react-native');
var Welcome = require('./welcome.ios');
var More = require('./more.ios');
var Todos = require('./todos.ios');
var { TabBarIOS, } = require('react-native-icons');

var {
  AppRegistry,
  TabBarIOS,
  Component
} = React;
```

**Comment by corymsmith** [comment]
The React declaration for TabBarIOS is overriding the one from
react-native-icons, you'll have to remove it.

var {
  AppRegistry,
  TabBarIOS, // Delete this line
  Component
} = React;

**Comment by jaysig** [comment]
That fixed it thanks a lot.

**Comment by corymsmith** [comment]
No worries!
