### ISSUE TITLE
Invariant violation error with Native 0.13.2 for android

### ISSUE THREAD

**Issue by MuruganDurai** [corymsmith/react-native-icons#140]
Hi, Good work with the icons. I am trying to add icons but getting the following error wherever. Could you please look into this? Do you have any solution or suggestion for this issue?

Invariant Violation: Element type is invalid:expected a string or class/function but got: object. Check the render method of 'myApp'

**Comment by corymsmith** [comment]
You'll have to share some of the code as somethings not quite right.

**Comment by MuruganDurai** [comment]
Thanks @corymsmith Below is the code.

'use strict';

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Image,  
  TextInput,  
  TouchableHighlight,
  ToastAndroid,
   ToolbarAndroid,
  ScrollView,  
} = React;

var Icon = require('react-native-icons');
var Container = require('./app/components/layout/Container');
var MovieItem = require('./app/components/movie/MovieItem');
var Tabbar = require('react-native-tabbar');
var Item = Tabbar.Item;
var precomputeStyle = require('precomputeStyle');

var myApp = React.createClass({

  getInitialState: function() {
    return {
      stores: [],
      loaded:false,
      name:'',
      selected:'Products',  
    };
  },

  onTabItemPress:function(name){
  console.log("clicked : " + name);
  this.setState({
    selected:name
  });
  },

  onChangeText: function(searchString){  
  console.log(searchString);
  if(searchString.length >= 2)
  {  
    this.fetchStores(searchString);  
  }else{
    this.setState({
      stores:[],  
    });
  }
  },

renderSearchResult: function(searchString){  
}

render: function() {
  console.log("Welcome to Zhopout");  
  if(this.state.loaded){
    return this.renderSearchResult();
  }
 var state = this.state
  return (  
<Container>
<ToolbarAndroid style={styles.toolbar} title='Zhopout'/>      

```
       <TextInput style={{height: 40, borderColor: 'green', borderWidth: 1, marginBottom: 10}} onChangeText={this.onChangeText.bind(this)}/>                                                      
       <Tabbar selected={state.selected} onTabItemPress={this.onTabItemPress}>

    <Item name="Products">
      <Item.Content>
        <View style={{ flex: 1,backgroundColor:'red'}}>
                <Text>Products</Text> 
                <View style={styles.QuickSearItems}>
                  <Text style={styles.year}>Mens Wear</Text>                      
                  <Text style={styles.year}>Now Open</Text>
                </View>                       
                <View style={styles.QuickSearItems}>
                  <Text style={styles.year}>Womens Wear</Text>                      
                  <Text style={styles.year}>Now Open</Text>
                </View>                       
                <View style={styles.QuickSearItems}>
                  <Text style={styles.year}>Shoes</Text>                      
                  <Text style={styles.year}>Now Open</Text>
                </View>                                           
        </View>
      </Item.Content>
      <Item.Icon>
          <Text>Products</Text>
      </Item.Icon>
    </Item>
    <Item name="Brands">
      <Item.Content>
        <View style={{ flex: 1,backgroundColor:'red'}}>
        <Text>Brands</Text> 
          <View style={styles.QuickSearItems}>
                  <Text style={styles.year}>Mens Wear</Text>                      
                  <Text style={styles.year}>Now Open</Text>
                </View>                       
                <View style={styles.QuickSearItems}>
                  <Text style={styles.year}>Womens Wear</Text>                      
                  <Text style={styles.year}>Now Open</Text>
                </View>                       
                <View style={styles.QuickSearItems}>
                  <Text style={styles.year}>Shoes</Text>                      
                  <Text style={styles.year}>Now Open</Text>
                </View>                                        
        </View>
      </Item.Content>
      <Item.Icon>              
          <Text>Brands</Text>
      </Item.Icon>
    </Item>
    <Item name="Stores">
      <Item.Content>
        <View style={{flex: 1,backgroundColor:'red' }}>
        <Text>Stores</Text> 
          <View style={styles.QuickSearItems}>
                  <Text style={styles.year}>Mens Wear</Text>                      
                  <Text style={styles.year}>Now Open</Text>
                </View>                       
                <View style={styles.QuickSearItems}>
                  <Text style={styles.year}>Womens Wear</Text>                      
                  <Text style={styles.year}>Now Open</Text>
                </View>                       
                <View style={styles.QuickSearItems}>
                  <Text style={styles.year}>Shoes</Text>                      
                  <Text style={styles.year}>Now Open</Text>
                </View>                                           
        </View>
      </Item.Content>
      <Item.Icon>   
```

<Icon
          name='octicons|alert'
          size={40}
          color='black'
          style={styles.alert}
        />  
              <Text>Stores</Text>
          </Item.Icon>
        </Item>
      </Tabbar>
       </Container>  
  );
},   

});

var styles = StyleSheet.create({
//all the styles implemented correctly 
});

AppRegistry.registerComponent('myApp', () => myApp);

**Comment by corymsmith** [comment]
Instead of:
var Icon = require('react-native-icons');

It should be:

var { Icon } = require('react-native-icons');

**Comment by MuruganDurai** [comment]
Thanks @corymsmith. Fixed it, but icons are not loaded instead vertical rectangle box is loaded (for ex. facebook icon with loaded with blue bgcolor & that box).

**Comment by corymsmith** [comment]
There's should be something in the logs, I'm guessing that the font isn't added to the project /  included in the Copy Resources phase

**Comment by MuruganDurai** [comment]
Thanks a ton and good learnings for me.

**Comment by corymsmith** [comment]
@MuruganDurai No worries, glad you got it sorted

**Comment by TASimpson** [comment]
@corymsmith I am facing the last issue where just a blank box is showing: 

![image](https://cloud.githubusercontent.com/assets/11613404/11580957/5fd1053c-9a02-11e5-8f33-ab3220818dd6.png)

However, all of the files from react-native-icons/fonts folder has been imported to android/app/src/main/assets as told by: https://www.npmjs.com/package/react-native-icons

![image](https://cloud.githubusercontent.com/assets/11613404/11580975/8d6d8a74-9a02-11e5-8548-93c94f203f74.png)


assets folder: 

![image](https://cloud.githubusercontent.com/assets/11613404/11580976/9c4f93b6-9a02-11e5-9b44-f77de82ac219.png)

I also have 
![image](https://cloud.githubusercontent.com/assets/11613404/11580981/b6870e76-9a02-11e5-8435-0b69b28c4896.png)
as also listed at https://www.npmjs.com/package/react-native-icons

here is my icon code: 
![image](https://cloud.githubusercontent.com/assets/11613404/11581002/eace6f9e-9a02-11e5-91fa-331169dc3a29.png)


HELP PLEASE :)
