### ISSUE TITLE
Size must be specified in styles

### ISSUE THREAD

**Issue by simonexmachina** [corymsmith/react-native-icons#143]
I thought this package wasn't working until I realised that I need to specify the size both in the props and in the styles. This seems unexpected to me. Maybe the docs should mention this if it is expected behaviour.

**Comment by mangogogos** [comment]
From readme:

"Icon style must set a width and height, or the icon will not be visible"

**Comment by corymsmith** [comment]
We should probably add a check warning to the code since this comes up quite a bit

**Comment by markburns** [comment]
Could you add a default value instead of a warning/docs? 

Anyone who needs to is going to actually see the size needs changing and work out how to change it themselves.

**Comment by corymsmith** [comment]
Closing this as support for this library is being discontinued, I highly recommend using https://github.com/oblador/react-native-vector-icons instead as its more fully featured, I've added a warning to the Readme about this as well.
