### ISSUE TITLE
error on compiling SMXTabBar.m

### ISSUE THREAD

**Issue by seanscal** [corymsmith/react-native-icons#144]
![image](https://cloud.githubusercontent.com/assets/7338055/11483612/4f613f42-9777-11e5-8598-cf6a344c9177.png)
I'm getting this error when I attempt to build my project.  Is this common? Has anyone run into this? 
Thanks for any info anyone can provide

the first error is line 97 after the first `_Nonnull`

**Comment by seanscal** [comment]
```
  [[self reactSubviews] enumerateObjectsUsingBlock:^(id  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {

    SMXTabBarItem *tab = [obj respondsToSelector:@selector(barItem)] ? (SMXTabBarItem*)obj : nil;

    if (tab){
      UIViewController *controller = _tabController.viewControllers[idx];
      controller.tabBarItem = tab.barItem;
      if (tab.selected){
        _tabController.selectedViewController = controller;
      }
    }

  }];

  /*
   [[self reactSubviews] enumerateObjectsUsingBlock:^(SMXTabBarItem *tab, NSUInteger index, BOOL *stop) {
   UIViewController *controller = _tabController.viewControllers[index];
   controller.tabBarItem = tab.barItem;
   if (tab.selected) {
   _tabController.selectedViewController = controller;
   }
   }];*/

}
```

uncommenting the second part of this and commenting out the first fixes the problem, I assume this is still an issue though, my obj-C isn't sharp enough to solve this myself

**Comment by corymsmith** [comment]
What version of this library are you using? And what version of React Native? I would guess that your React Nativeis out of date

**Comment by seanscal** [comment]
I'm using the most current version of this library and react native 0.14.2, is this too out of date?

**Comment by theoriginalgri** [comment]
_Nonnull was introduced with XCode 7. It looks like you're using a 6.x version?
