### ISSUE TITLE
Not working in Android

### ISSUE THREAD

**Issue by simonexmachina** [corymsmith/react-native-icons#145]
I've just created a new test project with react-native@0.15.0 and the Icons are not displaying in Android. I've pushed the test project [to Github](https://github.com/aexmachina/ReactNativeIconsTest) for your reference. Pretty sure I've done everything, but please do let me know if I've stuffed up somehow.

**Comment by simonexmachina** [comment]
I've also tried 0.14 and got the same result.

**Comment by peterwilli** [comment]
Yeah for me too

**Comment by peterwilli** [comment]
@aexmachina I figured it out!

I did the following, create a icon like this

```
<Icon
  style={styles.icon}
  name='fontawesome|android'
  size={70}
  color='#000'
/>
```

Declare the style:

```
var styles = StyleSheet.create({
  icon: {
    backgroundColor: '#3b5998',
    color: '#ffffff',
    width: 70,
    height: 70,
  },
});
```

Now it is visible on my end!

**Comment by simonexmachina** [comment]
Nope, that doesn't work for me. I see the background color, but not the icon.

**Comment by corymsmith** [comment]
@aexmachina I just figured out whats going on, you're missing https://github.com/corymsmith/react-native-icons/blob/master/Example/android/app/src/main/assets/fontawesome.json and https://github.com/corymsmith/react-native-icons/blob/master/Example/android/app/src/main/assets/ion.json from the assets directory, see: https://github.com/corymsmith/react-native-icons/tree/master/Example/android/app/src/main/assets

**Comment by simonexmachina** [comment]
Right, okay thanks. Yes that's fixed it. You might want to add that to the docs, especially because it's not required for iOS.

**Comment by simonexmachina** [comment]
Okay, it is there - was that added recently? Sorry if I missed it!
