### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by atom992** [corymsmith/react-native-icons#149]
Hi, my env: 
react-native-cli : 0.1.7 
react-native : 0.16.0 [react-native-icons](https://github.com/corymsmith/react-native-icons): 0.7.0  
when I run my app ,I got the following error: 
`E/ReactNativeJS( 2973): Can't find variable: Symbol`  
but the Example of react-native-icons works fine.

**Comment by corymsmith** [comment]
Can you share more of the error or logs? Like where that error is happening?

Thanks,
Cory Smith
On Wed, Dec 9, 2015 at 7:03 AM, corymsmith/react-native-icons
reply@reply.github.com
wrote:
Hi, my env:
react-native-cli : 0.1.7
react-native : 0.16.0 react-native-icons [https://github.com/corymsmith/react-native-icons] : 0.7.0

when I run my app ,I got the following error:
E/ReactNativeJS( 2973): Can't find variable: Symbol

but the Example of react-native-icons works fine.

**Comment by atom992** [comment]
there is no more error logs. the whole logs when the app running:

```
W/ReactNativeJS( 2973): Warning: Native component for "RCTMap" does not exist
W/ReactNativeJS( 2973): Warning: Native component for "RCTModalHostView" does not exist
W/ReactNativeJS( 2973): Warning: Native component for "RCTWebView" does not exist
I/ReactNativeJS( 2973): I'm `fs` modules
I/ReactNativeJS( 2973): Running application "My-ReactNative-Android-Demo" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
E/ReactNativeJS( 2973): Can't find variable: Symbol
```

**Comment by corymsmith** [comment]
Maybe try a clean and rebuild and make sure you've restarted the packager after
upgrading RN or this library as well

**Comment by corymsmith** [comment]
This doesn't appear to be an issue with this module. See https://github.com/facebook/react-native/issues/4587

**Comment by ranyefet** [comment]
I've used this polyfill and it fixed my problem: https://github.com/medikoo/es6-symbol
