### ISSUE TITLE
React-native 0.15.0 Incompatible block pointer types

### ISSUE THREAD

**Issue by jonolock91** [corymsmith/react-native-icons#151]
Hi, I've upgraded my react-native version to 0.15.0 and I'm having the following error which causes my build to fail in Xcode, any ideas? Thanks

<img width="1280" alt="screen shot 2015-12-09 at 14 04 21 copy" src="https://cloud.githubusercontent.com/assets/11156990/11687333/fa627872-9e7d-11e5-87a7-97ef5317466f.png">

**Comment by corymsmith** [comment]
What version of this library are you using? Try upgrading to the latest and
upgrading to RN 0.16.0

**Comment by corymsmith** [comment]
@jonolock91 Any luck?

**Comment by jonolock91** [comment]
I've created a new project because I had some other issues too and it's now working thanks.
