### ISSUE TITLE
'IconImage' has no propType for native prop 'SMXIconImage.renderToHeadwareTextureAndroid' of native type 'boolean' on Android

### ISSUE THREAD

**Issue by nickv118** [corymsmith/react-native-icons#154]
I am trying to use react-native-icons in my react native android project.

When i run the project in emulator, it throws this error.

Does anybody have a thought on this?

**Comment by corymsmith** [comment]
What version of React Native is in your package.json and in your gradle 
file.
Also what version of this library?
