### ISSUE TITLE
ToolbarAndroid

### ISSUE THREAD

**Issue by shukerullah** [corymsmith/react-native-icons#157]
Is there any way to use this with ToolbarAndroid?

``` javascript
var toolbarActions = [
  {title: 'Message', icon: require('image!ic_message_white'), show: 'always'},
  {title: 'Search', icon: 'ion|ios-search', show: 'always'},
  {title: 'Settings', show: 'never'},
];
```

Icons are working from drawable but not with plugin.
![screenshot_2016-01-21-20-14-26](https://cloud.githubusercontent.com/assets/963765/12484458/3b2e0720-c07c-11e5-9eaa-f6f330dbf14e.jpg)

**Comment by corymsmith** [comment]
A better option would be http://github.com/oblador/react-native-vector-icons as he's implemented this

**Comment by shukerullah** [comment]
@corymsmith thanks
