### ISSUE TITLE
RN to upgrade to 0.18 icon is not shown

### ISSUE THREAD

**Issue by mvpdream** [corymsmith/react-native-icons#159]

**Comment by jonolock91** [comment]
I'm on 0.19.0 and on Android the icons do not display either.

**Comment by jacob-russo** [comment]
Same issue here.

**Comment by xiekw2010** [comment]
My RN version is 0.19.0. 

I do all the steps as the readme guides except step3 include fonts

I do it in my MainActivity 

``` java
public class MainActivity extends ReactActivity {
    private CodePush _codePush;

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getJSBundleFile() {
        return this._codePush.getBundleUrl("index.android.bundle");
    }

    @Override
    protected String getMainComponentName() {
        return "GitFeed";
    }

    /**
     * Returns whether dev mode should be enabled.
     * This enables e.g. the dev menu.
     */
    @Override
    protected boolean getUseDeveloperSupport() {
        return BuildConfig.DEBUG;
    }

    /**
     * A list of packages used by the app. If the app uses additional views
     * or modules besides the default ones, add more packages here.
     */
    @Override
    protected List<ReactPackage> getPackages() {
        // 4. Instantiate an instance of the CodePush runtime, using the right deployment key

        // 5. Add the CodePush package to the list of existing packages
        return Arrays.<ReactPackage>asList(
                new MainReactPackage(), new ReactNativeIcons());
    }
}

```

I look up the .apk file, all the source file (json and ttf) was included.

But the icons doesn't show in my app.

**Comment by juncocoa** [comment]
Same issue here,Seeking solutions

**Comment by makexxoo** [comment]
+1

**Comment by ghamaide** [comment]
+1, RN 0.19.0

**Comment by cmmouritsen** [comment]
I do not believe this is going to be fixed. Please note this message from the home page of this project:

WARNING: Support for this library is being discontinued, I highly recommend using https://github.com/oblador/react-native-vector-icons instead as its more fully featured.

In order to upgrade to RN 0.19, I had to switch my icons over to react-native-vector-icons. It wasn't too bad. Good luck!

**Comment by corymsmith** [comment]
That is correct, I recommend migrating over ASAP.

**Comment by corymsmith** [comment]
Closing this as support for this library is being discontinued, I highly recommend using https://github.com/oblador/react-native-vector-icons instead as its more fully featured, I've added a warning to the Readme about this as well.
