### ISSUE TITLE
Build with react 0.3.11 fails with linked .a file, but works when adding source files

### ISSUE THREAD

**Issue by jsierles** [corymsmith/react-native-icons#16]
If I add the .a file from Products, the build mysteriously fails with no errors. If I remove this file, but instead add the entire IOS directory to the project, the build succeeds.

**Comment by EvanJin** [comment]
@jsierles  how did you solved it?

**Comment by jsierles** [comment]
By adding the IOS directory directly to the project via 'Add Files'. It's not required to link the .a file.
