### ISSUE TITLE
MainActivity.java and assets path is not as described

### ISSUE THREAD

**Issue by idangozlan** [corymsmith/react-native-icons#160]
MainActivity.java file is pretty different from the one on the guide, also assets dir path is not exist.
I think that the newer version of react native is different than the one that you guide about.

**Comment by corymsmith** [comment]
Closing this as support for this library is being discontinued. I highly recommend using https://github.com/oblador/react-native-vector-icons instead as its more fully featured, I've added a warning to the Readme about this as well.
