### ISSUE TITLE
*** Assertion failure in +[FAKIonIcons registerIconFontWithURL:], 

### ISSUE THREAD

**Issue by robtg4** [corymsmith/react-native-icons#161]
I get the following error and I have made no changes to my code (from when this was working without error). Now I receive the following: 

```
*** Assertion failure in +[FAKIonIcons registerIconFontWithURL:], /Applications/MAMP/htdocs/blaclist/node_modules/react-native-icons/ios/ReactNativeIcons/Libraries/FontAwesomeKit/FAKIcon.m:14
2016-02-16 01:59:22.298 blaclist[74426:56845999] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Font file doesn't exist'
```

**Comment by corymsmith** [comment]
I highly recommend using https://github.com/oblador/react-native-vector-icons instead as its more fully featured, I've added a warning to the Readme about this as well.
