### ISSUE TITLE
Seems you're trying to access 'ReactNative.createClass' from 'react-native' package.

### ISSUE THREAD

**Issue by hoseinmobasher** [corymsmith/react-native-icons#165]
Hello,
I have a problem with using your library. I followed your guidelines but the problem has occurred.
When I want to import your module using `var Icon = require('react-native-icons')` following error occurs.

> Seems you're trying to access 'ReactNative.createClass' from 'react-native' package. Perhaps you meant to access 'React.createClass' from the 'react' package instead?

What should I do?

Regards

**Comment by corymsmith** [comment]
This library is deprecated, use react-native-vector-icons
