### ISSUE TITLE
Icons aren't showing after upgrade to 0.0.3

### ISSUE THREAD

**Issue by michalraska** [corymsmith/react-native-icons#17]
Hi,
after upgrade to react-native 0.3.11 and icons to 0.0.3 icons aren't displaying. I am also using SMXTabBar in project and in console I can see warning: `[tid:com.facebook.ReactKit.ShadowQueue][RCTUIManager.m:738] No manager class found for view with module name "SMXTabBar"`. TabBar is not displaying at all too.
Maybe I made mistake in step 7, witch files should be added? Only *.ttf | *.otf ?

**Comment by corymsmith** [comment]
Check the User Header Search paths, I think you'll have to add them to the ReactNativeIcons.xcodeproj.

I'll have to find a better way to do that in the future

**Comment by michalraska** [comment]
Yes, as you can see:
![image](https://cloud.githubusercontent.com/assets/827753/7203426/e54e09f0-e51a-11e4-90ff-1407c5eec7b4.png)

**Comment by michalraska** [comment]
I am sorry, my fault.
I had libReactNativeIcons.a file in copy bundle instead in libraries and somehow was possible to build project.
Thank you for this package. Great work.

**Comment by corymsmith** [comment]
Perfect, glad you got it working
