### ISSUE TITLE
Adding project to package.json and npm installing breaks the app

### ISSUE THREAD

**Issue by josebalius** [corymsmith/react-native-icons#18]
@corymsmith This is probably something else I am missing but I narrowed it down to the following

```
Step 1 - 'react-native init TestProject' // using react-native 0.4

After adding react-native-icons to package.json
Step 2 - npm install
```

Run app, and it just hangs after the splash screen. If I remove the react-native-icons from the node_modules folder and re run the app, it loads just fine, have you encountered this?

Thanks

Jose

**Comment by ptmt** [comment]
maybe related to https://github.com/facebook/react-native/issues/917

**Comment by mwilc0x** [comment]
I found that upgrading my apps dependencies to use react-native 0.4.0 has fixed this problem for a couple other packages I am using.

**Comment by ptmt** [comment]
@mjw56 Me too. May be `peerDependency` or npm3 will help to avoid of deduplicating react-native?

**Comment by mwilc0x** [comment]
@unknownexception yeah, trying to get an idea of what the best approach might be to prevent this in the future. It seems peerDependencies could have prevented this.

**Comment by corymsmith** [comment]
Yeah I'm curious what The best approach is as well. I'll upgrade it to 0.4.0 today as a first step

**Comment by corymsmith** [comment]
Upgraded to React Native 0.4.0, should I be declaring react-native as a peerDependency, seems like it may be the best option?

**Comment by mwilc0x** [comment]
It looks like that is what some other packages have started to do, i.e. react-native-video, react-native-camera

I think that might be the best option that could prevent this in the future.

**Comment by corymsmith** [comment]
K sounds good, I'll publish a new version (0.0.5) in a few mins that moves it to peerDependencies

**Comment by mwilc0x** [comment]
cool! :smile:

**Comment by josebalius** [comment]
It's working for me now, thanks @corymsmith and everyone else.
