### ISSUE TITLE
Subspec to include different font icons

### ISSUE THREAD

**Issue by paramaggarwal** [corymsmith/react-native-icons#19]
Would you be open to the idea of having multiple subspecs for different font icons? This would allow the ease of using pods, but without adding each and every font to the app.

**Comment by corymsmith** [comment]
@paramaggarwal I had thought about this a bit, think it needs a bit more thought as to how best to go about it

**Comment by corymsmith** [comment]
I don't plan on implementing this so going to close this for now.
