### ISSUE TITLE
Ideas to integrate into the TabBar?

### ISSUE THREAD

**Issue by josebalius** [corymsmith/react-native-icons#2]
Wondering what your ideas were for using this library in the TabBar? I would love to help make that happen!

**Comment by corymsmith** [comment]
I was just thinking about that, going to roll out a custom Tab bar item that allows you to use an icon in the same way

**Comment by chadobado** [comment]
+1 :)

**Comment by corymsmith** [comment]
In the works!

Thanks,

Cory Smith
http://ca.linkedin.com/in/corysmith/
http:/twitter.com/smixx http://twitter.com/smixx

**Comment by josebalius** [comment]
Awesome @corymsmith let us know if you want any help.

**Comment by corymsmith** [comment]
@josebalius @chadobado Just added a custom tab bar and published to npm :) Let me know if you have any issues installing.

**Comment by scottwall0** [comment]
@corymsmith my project fails to build every time I add libReactNativeIcons.a to the Link Binary with Libraries build phase of my project. Any idea why that may be or how I can work around it? I've been trying to work it out but it doesn't seem to.

**Comment by viscasillas** [comment]
I can't get the icons to work at all. i have followed the installation instructions. But it the tabs just show up blank.

<code>
  <TabBarIOS selectedTab={this.state.selectedTab}>
                <TabBarIOS.Item
                    selected={this.state.selectedTab === 'AllTasks'}
                    name="home"
                    iconName={'ion|ios-home-outline'}
                    title={''}
                    iconSize={32}
                    onPress={() => {
                        this.setState({
                            selectedTab: 'AllTasks'
                        });
                    }}>
                    <TasksMainContainer/>
                </TabBarIOS.Item>
</code>

**Comment by corymsmith** [comment]
@viscasillas You will have to apply a style with a width and height as well
