### ISSUE TITLE
Icon not showing

### ISSUE THREAD

**Issue by georgiana-gligor** [corymsmith/react-native-icons#26]
Hi! I followed the instructions in other issues and successfully set the search path.
![search-path](https://cloud.githubusercontent.com/assets/1164711/7408579/c2a54010-ef26-11e4-82df-e481cb6d025e.png)

I also linked the library and exported the font:
![linked-libraries](https://cloud.githubusercontent.com/assets/1164711/7408581/c2a71f98-ef26-11e4-82e5-b6f2f18bba10.png)

However, the icon is not showing.
![icon-not-showing](https://cloud.githubusercontent.com/assets/1164711/7408580/c2a5d138-ef26-11e4-9ca5-6b04eaadd938.png)

My code is

```
var Icon = require('FAKIconImage');

// ......

        <Text>Blah 1</Text>
        <Icon
          name='foundation|lightbulb'
          size={30}
          color='#777777'
          style={styles.lightbulb}
        />
        <Text>Blah 2</Text>
```

As you can see, only the surrounding text is showing up.

**Comment by corymsmith** [comment]
Are there any errors in the logs? The search path should be set to recursive as well. In the latest version the search path is already included in the XCode project so you shouldn't have to set it. What version do you have installed?

**Comment by corymsmith** [comment]
@georgiana-gligor Did you end up getting this resolved?

**Comment by georgiana-gligor** [comment]
Unfortunately not yet. I can't see any warning or error in the Chome debug window, nor in XCode.

**Comment by georgiana-gligor** [comment]
I am working with the latest version of everything, this also applies to react native.

**Comment by gnoff** [comment]
I am also having the same problem. no errors in console or in xcode. project builds fine. but no icon appearing in view.

**Comment by gnoff** [comment]
OK for me the issue was i wasn't styling the icon. once i styled with a height and width everything worked fine.

This brings up a question though. What is the Size prop and how is it related to the style for height and width. It looks like you need to set both to get things working properly, is that not something that is just redundant?

Thanks for any help/insight

**Comment by deanc** [comment]
@gnoff this was also the issue I had. Make sure to give your `Icon` tags style with width/height and they'll show up.

**Comment by georgiana-gligor** [comment]
I had width set but not height. Forcing both did the trick.
Thanks all!
