### ISSUE TITLE
Compatible w/ React-native 0.4.1?

### ISSUE THREAD

**Issue by chadobado** [corymsmith/react-native-icons#28]
Trying to get this installed again and having problems.

Thanks in advance.

**Comment by JonasJonny** [comment]
Actual version is compatible. I am using it without problems. Maybe you can provide more details.

**Comment by chadobado** [comment]
Sorry, slammed ATM - will circle back next week.  Also will likely submit a PR to update installation instructions with images if you think it'd be helpful.  

Not sure why I tank install for every project I add this to.

Wonderful library though! :)

**Comment by deepure** [comment]
![image](https://cloud.githubusercontent.com/assets/1285533/7614587/5be1d77c-f9ca-11e4-8059-b2bdc377c56e.png)
both in RN 0.4.1 and RN 0.4.2 with react-native-icons 0.0.5

**Comment by stuartlynn** [comment]
Having the same issue here. Crashes in exactly the same place. React native 0.4.2 and react-native-icons 0.0.5

**Comment by corymsmith** [comment]
My guess would be that the font files aren't included in the target. Make sure that the ion icons font file is included in the copy resources phase.

**Comment by corymsmith** [comment]
Updated for React Native 0.4.3 and published as 0.0.7
