### ISSUE TITLE
Impossible to change selected icon

### ISSUE THREAD

**Issue by seestems** [corymsmith/react-native-icons#29]
It is no way to change icon for active/inactive state.

**Comment by corymsmith** [comment]
@chessman2 You would just have to render a different icon for that state, I've used that for checkboxes, radio buttons, etc

**Comment by kevinaltschuler** [comment]
how did you rerender? right now i have the icon's name in a variable and im changing the name based on the state.. but it seems like its not rerendering

heres my render function if youre willing to help 

http://pastebin.com/LWpsubkf
