### ISSUE TITLE
Example crashes because of redundant code in FAKZocial.m

### ISSUE THREAD

**Issue by bparadie** [corymsmith/react-native-icons#36]
https://github.com/corymsmith/react-native-icons/blob/master/iOS/ReactNativeIcons/Libraries/FontAwesomeKit/FAKZocial.m#L9-L16

```
#ifndef DISABLE_ZOCIAL_AUTO_REGISTRATION
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSURL *resourcesBundleUrl = [[NSBundle mainBundle] URLForResource:@"ReactNativeIconsResources" withExtension:@"bundle"];
        NSBundle *bundle = [NSBundle bundleWithURL:resourcesBundleUrl];
        [self registerIconFontWithURL: [[NSBundle mainBundle] URLForResource:@"zocial-regular-webfont" withExtension:@"ttf"]];
    });
#endif
```

`bundle` is never used but crashes, because there is no `ReactNativeIconsResources.bundle`:

![screen shot 2015-05-21 at 12 28 47 pm](https://cloud.githubusercontent.com/assets/1578115/7757112/ae233bc6-ffb4-11e4-9c01-58fd90ba4fd4.png)

**Comment by mvayngrib** [comment]
fixed in https://github.com/corymsmith/react-native-icons/pull/43

**Comment by corymsmith** [comment]
@mvayngrib Thanks for the PR! Just published the latest to NPM
