### ISSUE TITLE
Push then Pop breaks SMXTabBarIOS

### ISSUE THREAD

**Issue by dorthwein** [corymsmith/react-native-icons#37]
I have SMXTabBarIOS and Navigator set up, when you push something ontop of the tabs, then pop that scene, the scene with the tabs is broken.

**Comment by dorthwein** [comment]
Issue had to do with some of the View wrappers - not sure why but removing alignItems: 'center' on the container addressed the issue,

**Comment by dvdhsu** [comment]
I have the same problem, @dorthwein, do you mind explaining how you fixed it? Did you remove the alignItems on the view containers in the pushed views? Or did you remove it from the original view, which contains the tabs?

Thanks!

**Comment by dorthwein** [comment]
@dvdhsu It was awhile ago - but I think it was on the container views.  I've included a stripped down version of all the styles I have applied for the basic view.  I also stopped using landscape view. 

The only styles I have are as follows:

```
var SCREEN_WIDTH = DIMENSIONS.get('window').width;
var SCREEN_HEIGHT = DIMENSIONS.get('window').height;

```

```
<SMXTabBarIOS style={[{    flex: 1, width: SCREEN_WIDTH, height: SCREEN_HEIGHT, }]} >
      <SMXTabBarItemIOS>
             <View style={[{flex:1}]}>
                      {YOUR CONTENT ETC...}
             </View>
      </SMXTabBarItemIOS>
</SMXTabBarIOS>
```
