### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by ckrad** [corymsmith/react-native-icons#39]
it's not work. my app crashed.

```
#ifdef __BLOCKS__
__OSX_AVAILABLE_STARTING(__MAC_10_6,__IPHONE_4_0)
DISPATCH_EXPORT DISPATCH_NONNULL_ALL DISPATCH_NOTHROW
void
dispatch_once(dispatch_once_t *predicate, dispatch_block_t block);

DISPATCH_INLINE DISPATCH_ALWAYS_INLINE DISPATCH_NONNULL_ALL DISPATCH_NOTHROW
void
_dispatch_once(dispatch_once_t *predicate, dispatch_block_t block)
{
    if (DISPATCH_EXPECT(*predicate, ~0l) != ~0l) {
        dispatch_once(predicate, block); // crashed here
    }
}
#undef dispatch_once
#define dispatch_once _dispatch_once
#endif
```

**Comment by ckrad** [comment]
sorry my bad. it worked. i just did it wrong.

**Comment by marclundgren** [comment]
@ckrad I got the same error when trying to run the example script. What were you doing wrong?

**Comment by corymsmith** [comment]
@ckrad How did you end up fixing this?

**Comment by arunshan** [comment]
@ckrad Could you please let us know how you fixed this issue?

**Comment by ffxsam** [comment]
Could someone please post a response on how to fix this? I followed the instructions step by step, and I'm getting the same problem.

**Comment by idrakimuhamad** [comment]
As reported in #128 , it appears that loading the font file individually seems to solve the problem. If you choose the folder and import it, something somewhere breaks it.
