### ISSUE TITLE
Icons as image assets

### ISSUE THREAD

**Issue by 0x0ece** [corymsmith/react-native-icons#41]
Hi, it would be great to have a way to get icons as image assets as well, so to be used wherever react native allows for an Image.propTypes.source. Make sense? Is it a dream? :)

**Comment by corymsmith** [comment]
@ecesena Unfortunately I don't see a way to make that work considering how React Native internally looks for image assets

**Comment by 0x0ece** [comment]
Thanks Cory, that's a pity -- world be awesome!
