### ISSUE TITLE
does not work with the newest react-native 0.4.4

### ISSUE THREAD

**Issue by pgmemk** [corymsmith/react-native-icons#42]
I would love to use your component in our react-native chat app. 
I can see several cases where I want to use it instead of Images

 BUT!!!

When building the project Xcode complains that it could not find node_modules/react-native/Libraries/ReactIOS/ReactIOSViewAttributes. And in fact this source is not there anymore (or anywhere for that matter). 

Could you please take a look.

**Comment by pgmemk** [comment]
My bad I didn't update to the newest version of react-native-icons.

**Comment by corymsmith** [comment]
@pgmemk Glad you got it sorted! Was at a music festival for the past 5 days so just got this now :)
