### ISSUE TITLE
linker command failed

### ISSUE THREAD

**Issue by ladas-larry** [corymsmith/react-native-icons#44]
Just after I added react-native-icons into my project, I've got this issue:
![screen shot 2015-05-29 at 08 28 38](https://cloud.githubusercontent.com/assets/3543614/7877535/f1959a10-05dc-11e5-86e9-a5912543a905.png)

**Comment by ladas-larry** [comment]
sorrry, I've made mistake during installation

**Comment by tmtk75** [comment]
@Dharmoslap How did you solve this? Do you remember? I'm stuck at the same error. It would be helpful if you could give me an advice.

**Comment by tmtk75** [comment]
I also was able to solve this. Mistakenly it seemed I added the library twice during setting up.
