### ISSUE TITLE
Question: possible to add a css class for spinner?

### ISSUE THREAD

**Issue by steve-ng** [corymsmith/react-native-icons#46]
Inside font-awesome, in order to make it spin, we can add a css class fa-spin.

possible in react-native-icons?

http://fortawesome.github.io/Font-Awesome/examples/#animated

**Comment by tikhonbelousko** [comment]
React native doesn't have CSS classes, it uses StyleSheet objects instead which doesn't have animations. Property for spinning can be added though. Noteworthy, you can implement spinning animation on your own using [TweenState](https://github.com/chenglou/react-tween-state) and [transform styles](https://facebook.github.io/react-native/docs/transforms.html#content).

Honestly, I would use [standard iOS indicator](https://facebook.github.io/react-native/docs/activityindicatorios.html).

**Comment by corymsmith** [comment]
@steve-ng Exactly what @DaZzz said :) You can use animations to spin any component so that would work for these icons / images as well.
