### ISSUE TITLE
Could you update the peer dependency version for react-native 0.5?

### ISSUE THREAD

**Issue by joewood** [corymsmith/react-native-icons#47]
**npm** is reporting a dependency check failure with the current version of react-native-icons in npm.

**Comment by piyushchauhan2011** [comment]
yep same problem. I'm hoping they can release newer version with 0.6 version of react-native.

**Comment by corymsmith** [comment]
I'll take care of this today!

**Comment by piyushchauhan2011** [comment]
@corymsmith Thanks mate, appreciate your work.

**Comment by corymsmith** [comment]
Just published 0.0.9 to NPM

**Comment by corymsmith** [comment]
Updated to React Native 0.5.0 for now
