### ISSUE TITLE
[Bug? Using Icon] Invariant Violation: Expected a component class, got undefined.

### ISSUE THREAD

**Issue by MossP** [corymsmith/react-native-icons#48]
Thanks for the plugin. Potentially a great help :)
However, I have successfully added the icons to a custom tab bar but attempting to use an icon in a regular view causes this error. Any ideas?

```
Invariant Violation: Expected a component class, got undefined.
<unknown>
ReactNativeDefaultInjection.js:101

getComponentClassForElement
ReactNativeComponent.js:59
```

React-Native v0.4.4
React-Native-Icons v0.0.9

**Comment by corymsmith** [comment]
I think you'll have to upgrade RN to 0.5.0

**Comment by MossP** [comment]
Thanks for getting back to me, I've just found out what it was. I had "Icon" in my destructuring declaration e.g.

```
var {
  blah,
  blah,
  blah,
  Icon
} = React;
```
