### ISSUE TITLE
React-Native dependency

### ISSUE THREAD

**Issue by grabbou** [corymsmith/react-native-icons#49]
Hey,
Why the `0.4.x` is no longer supported with the latest release?
Is it possible to add `0.6` support as well?

**Comment by lazywei** [comment]
+1 for this
i'd like to upgrade RN to 0.6.0-rc

**Comment by corymsmith** [comment]
I just pushed an update to npm that supports > 0.5.0, I'm trying to stay up to date as RN changes, since its changing so quickly its hard to support the latest versions and lower ones as well.
