### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by naartjie** [corymsmith/react-native-icons#5]
Hey @corymsmith 

For installation, I had to do step 5. (Drag ReactNativeIconsResources.bundle into the Copy Bundle Resources build phase) for both my project and the ReactNativeIcons project. Could you verify that's correct? I can do a PR to update the Readme.

https://github.com/corymsmith/react-native-icons/blame/22dc49dd3cfa3e1fd4c0a6ec3f4c466a239fe5a5/README.md#L22

**Comment by cuongvo** [comment]
Had to do the same thing :+1:

**Comment by rymdluo** [comment]
Hi could you elaborate the installation process? My build keeps failing though I think followed the instructions (including dragging ReactNativeIconsResources.bundle into both projects) correctly.

**Comment by corymsmith** [comment]
@naartjie @cuongvo I think that may be the case, if you want to do a PR that would be great, just on the road driving most the day today. I'll have to sort out the best way to copy / include that bundle. Hoping once the react-extension-manager stuff is further along that the install can be just 1 step.

**Comment by corymsmith** [comment]
@rymdluo What errors are you getting?

**Comment by crapthings** [comment]
how to get step 6 work ?

Click ReactNativeIcons.xcodeproj in the project navigator and go the Build Settings tab. Look for User Search Paths and make sure it contains both $(SRCROOT)/../../react-native/React, make sure to set it as recursive.

**Comment by cuongvo** [comment]
@crapthings It's under "Search Paths" and the full name is "User Header Search Paths". Double clicking on that after entering it will display a popup to set the search path recursive.

**Comment by dmnkgrc** [comment]
Hi, I get this error when building my project, I copied the bundle to both projects, but I don't know in which step did I do something wrong.
error: /Users/dominikgar/Library/Developer/Xcode/DerivedData/Stimung-bthydlpfzlhetnewznudfqwlalie/Build/Products/Debug-iphonesimulator/ReactNativeIconsResources.bundle: No such file or directory

**Comment by corymsmith** [comment]
@dominikgar Can you try to drag ReactNativeIconsResources.bundle into the Copy Bundle Resources build phase of the ReactNativeIcons project as well?

**Comment by dmnkgrc** [comment]
@corymsmith I already tried that :(

**Comment by corymsmith** [comment]
@dominikgar That should fix it, maybe retry the install process from the beginning?

**Comment by crapthings** [comment]
CpResource /Users/monsterstep/Library/Developer/Xcode/DerivedData/test-cxozodmgdemszseiellbhltfivxm/Build/Products/Debug-iphonesimulator/ReactNativeIconsResources.bundle /Users/monsterstep/Library/Developer/Xcode/DerivedData/test-cxozodmgdemszseiellbhltfivxm/Build/Products/Debug-iphonesimulator/test.app/ReactNativeIconsResources.bundle
    cd /Volumes/Data/dev/test
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/monsterstep/Library/Developer/Xcode/DerivedData/test-cxozodmgdemszseiellbhltfivxm/Build/Products/Debug-iphonesimulator/ReactNativeIconsResources.bundle /Users/monsterstep/Library/Developer/Xcode/DerivedData/test-cxozodmgdemszseiellbhltfivxm/Build/Products/Debug-iphonesimulator/test.app

error: /Users/monsterstep/Library/Developer/Xcode/DerivedData/test-cxozodmgdemszseiellbhltfivxm/Build/Products/Debug-iphonesimulator/ReactNativeIconsResources.bundle: No such file or directory

Get these error after compile.

**Comment by corymsmith** [comment]
@crapthings This is usually fixed by: Also dragging ReactNativeIconsResources.bundle into the Copy Bundle Resources build phase of the ReactNativeIcons project as well. I've updated the Readme to reflect that today

**Comment by jbhatab** [comment]
I'm not even getting the bundle to appear under projects? Where is the bundle?

**Comment by naartjie** [comment]
Hi @jbhatab, mine is here, under `ReactNativeIconx.xcodeproj` / `Products`
![screen shot 2015-04-14 at 14 47 54](https://cloud.githubusercontent.com/assets/514563/7136894/59ead9cc-e2b5-11e4-817f-62944bee6aa5.png)

**Comment by jbhatab** [comment]
Ok I see where it ended up getting added, but I'm not getting the right way to add things.

I right clicked on libraries and clicked add files to 'project' but it won't let me add the xcodeproject. It shows up as unselectable. So I just added it in another place and dragged it down. But then when I add the resources to the main project from the react native icons products section it doesnt work.

Is there a right and wrong way to import libraries?

**Comment by corymsmith** [comment]
I just updated this module to remove the .bundle requirement. Instead you include the font files you use. I've published 0.0.2 to NPM and also updated the install instructions.

**Comment by jbhatab** [comment]
Still so many questions and not working. I'm just going to keep going at this and I think it's really my lack of xCode knowledge preventing me from getting this working.

Thanks for the update!

**Comment by corymsmith** [comment]
I'm in the Slack group (Smixx) if you have specific questions :)
