### ISSUE TITLE
Push and pop breaks SMXTabBarIOS

### ISSUE THREAD

**Issue by dvdhsu** [corymsmith/react-native-icons#50]
Much like #37, but occurs with just the library, and no views.

To replicate, just make a SMXTabBarIOS, then in one of the tabs, attempt to push another view on top. When that top view is popped, the tab bar (which is on the bottom) is entirely broken. 

![ios simulator screen shot jun 16 2015 3 15 47 am](https://cloud.githubusercontent.com/assets/1313773/8174558/fe3a38be-13d5-11e5-89e8-6e98ad2bd1d1.png)

**Comment by dvdhsu** [comment]
Turns out this issue was because of changes in React Native's own RCTTabBar that were not applied back in to this library. I've created a PR that applies such changes back.

(The PR also fixes issues with device rotation, mentioned in the original issue.)

**Comment by corymsmith** [comment]
Fixed w/ #51
