### ISSUE TITLE
Font Icons Not Showing

### ISSUE THREAD

**Issue by ghost** [corymsmith/react-native-icons#52]
I followed through Getting Started instructions and I'm using the code from Example/index.ios.js.

My issue is that I don't see any of the font icons rendering on the simulator.

![ios simulator screen shot jun 15 2015 9 46 12 pm](https://cloud.githubusercontent.com/assets/1529857/8175958/10073b10-13a8-11e5-8413-ec41c011cc85.png)

I don't see any error messages on React Packager responses on Terminal, but I see some error messages displaying on chrome console.

![screen shot 2015-06-15 at 9 45 45 pm](https://cloud.githubusercontent.com/assets/1529857/8175960/188228f4-13a8-11e5-87e1-f467ae3e020d.png)

Can someone point me in the right direction to resolve this issue?

**Comment by corymsmith** [comment]
I'm guessing that you may have missed a step. I'd try to go through the steps again if I were you. It doesn't appear that the code is included correctly

**Comment by ghost** [comment]
Thanks for the response, I'll follow-up after double checking the code and going through steps again.

**Comment by austin1030** [comment]
+1 I think I follow the steps correctly but don't see icon and get same error message.

Any thought?

**Comment by corymsmith** [comment]
Could be that the header search path is incorrect? I would double check that

**Comment by austin1030** [comment]
When I set the header search path, which folder point to?

**Comment by austin1030** [comment]
OK, I resolved issue with "No manager class found...". Apparently for some reason I add libReactNativeIcons.a into ReactNativeIcons.xcodeproj instead of my own project. Now I see that instruction says "to your project." :)

Next problem. When my app gets to call below code, It get stuck "dispatch_once(predicate, block);" 
<Icon
  name='fontawesome|facebook-square'
  size={70}
  color='#3b5998'
  style={styles.facebook}
/>

Any idea?

**Comment by corymsmith** [comment]
I'm guessing the font files aren't included in the target?

**Comment by austin1030** [comment]
Did I add font files properly?
![screen shot 2015-06-19 at 6 03 39 pm](https://cloud.githubusercontent.com/assets/9681461/8263890/a00d98c8-16ad-11e5-964b-83e66e2194b6.png)

**Comment by ghost** [comment]
Thanks @austin1030, my issue was that I imported libReactNativeIcons.a into ReactNativeIcons.xcodeproj. I fixed this and I can now see the icon on the simulator.

In regards to the font file addition to Copy Bundle Resources, I imported the otf and ttf files.

**Comment by austin1030** [comment]
Thank you @jhprks! That resolve my issue. I wasn't sure which files or folder to import. Awesome!

**Comment by ghost** [comment]
Good to know that helped! Well, looks like this one is resolved.

**Comment by corymsmith** [comment]
Glad you got this sorted, thanks for helping out Ji
