### ISSUE TITLE
Icons being clipped

### ISSUE THREAD

**Issue by marcshilling** [corymsmith/react-native-icons#55]
The zocial Twitter icon (and many of their other ones) is being clipped.

``` javascript
<FAKIconImage name={'zocial|twitter'} size={50} style={{width:50, height: 50}} color='white' />
```

![Image of clipping](http://i.imgur.com/suXVJ6B.png)

I've tried messing with the both the `size` prop, and what I pass to `width` and `height`, but it keeps clipping.

**Comment by corymsmith** [comment]
What is that view wrapped in? The view itself doesn't look square, just
curious if thats the issue

Thanks,

Cory Smith
http://ca.linkedin.com/in/corysmith/
http:/twitter.com/smixx http://twitter.com/smixx

**Comment by marcshilling** [comment]
Nope, even if I make the icon my very top level view it is still clipped:

``` javascript
<View style={{flex: 1, backgroundColor: 'black', paddingTop: 20}}>
   <FAKIconImage name={'zocial|twitter'} size={50} style={{width:50, height: 50}} color='white' />
</View>
```

![clipped](http://i.imgur.com/N65lecV.png)

**Comment by marcshilling** [comment]
This is just an issue with zocial, btw. If I use `fontawesome|twitter`, it works great.

**Comment by irfaan** [comment]
I am experiencing clipping with fontawesome|keyboard-o

**Comment by irfaan** [comment]
@corymsmith Did you have any thoughts as to the source of this issue?

**Comment by corymsmith** [comment]
It has to do with the image scaling mode and the fact that those icons aren't equal width & height. I haven't had time to look into it though

**Comment by ffxsam** [comment]
I'm experiencing this in FontAwesome too. For example, check out `fontawesome|bicycle` and `fontawesome|diamond`.

**Comment by ffxsam** [comment]
The problem might lie in this section of code:
https://github.com/corymsmith/react-native-icons/blob/6a2e9c532d8dde7d90a6ce7593971dfd2f1a039e/iOS/ReactNativeIcons/Libraries/FontAwesomeKit/FAKIcon.m#L118-L134

I'm not totally sure, as I don't know much about Objective-C. But basically I think the solution would be to find the actual aspect ratio of the font icon, and then if one of its dimensions exceeds the `size` parameter passed to the React component, shrink that value to equal `size` while also reducing the other dimension by the same ratio.

**Comment by corymsmith** [comment]
@ffxsam You should check out https://github.com/oblador/react-native-vector-icons

He's fixed all these issues in his lib, I'm most likely discontinuing support on this lib to focus on pushing forward other open source projects. There's no need for competing icon libs that do the same thing :)

**Comment by ffxsam** [comment]
Oh man, thanks for the link! You saved me from spending hours later on trying to fix this. ;) Maybe you could include a note to this effect on the npmjs page, so people don't stumble down the same path I did.

**Comment by corymsmith** [comment]
@ffxsam Just added a warning now
