### ISSUE TITLE
Ionic icons not working

### ISSUE THREAD

**Issue by evanmrose** [corymsmith/react-native-icons#60]
When I try to reference an ionic icon (ionic ios icons work fine) like so:

```
<Icon
    name='ion|mic-a'
    size={50}
    color={'#f7f5ff'}
    style={styles.audioCreateIcon}
     >
</Icon>
```

Ios icons work fine but with normal ionic icons I get an error EXC Bad Instruction.

**Comment by corymsmith** [comment]
I'm guessing that the name of the icon is different in the generated code? What icon are you trying to use?

**Comment by fabiomcosta** [comment]
@evanmrose make sure you are setting a width and height on your styles https://github.com/corymsmith/react-native-icons#notes

**Comment by corymsmith** [comment]
@evanmrose Did you get this working?  This is working for me
