### ISSUE TITLE
Cannot find module 'FAKIconImage'

### ISSUE THREAD

**Issue by stephenhandley** [corymsmith/react-native-icons#63]
I'm getting the following error after following the 6 steps in the readme getting started. 

<img width="365" alt="screen shot 2015-07-05 at 1 58 58 pm" src="https://cloud.githubusercontent.com/assets/3257/8513389/56e2c5d8-231e-11e5-996e-62b8745d02d3.png">

The project builds fine, it just breaks on this require in my app when it runs.

```
Icon  = require('FAKIconImage')
```

I'm using [react-native-webpack-server](https://github.com/mjohnston/react-native-webpack-server) so wondering whether the issue may be related to that. 

Any help would be much appreciated!

**Comment by alinz** [comment]
It could be related to #61

**Comment by corymsmith** [comment]
I'm hoping to fix a bunch of these issues and upgrade for the latest version of RN today / tomorrow.

**Comment by alinz** [comment]
@corymsmith are you aware of this issue https://github.com/facebook/react-native/issues/1808. if you need help I can provide a pull request for that.

More info: you can also take a look at the [release note](https://github.com/facebook/react-native/releases/tag/v0.7.0-rc) **Breaking Changes**.

**Comment by mnylen** [comment]
@alinz, @corymsmith - see also https://github.com/corymsmith/react-native-icons/issues/59

**Comment by corymsmith** [comment]
@mnylen @alinz @stephenhandley Just published version 0.2.0 to NPM, you'll have to change the require to be require ("react-native-icons").Icon
