### ISSUE TITLE
react 0.60 breaking react-native-icon

### ISSUE THREAD

**Issue by steve-ng** [corymsmith/react-native-icons#64]
Hi Im getting the error of 

EXC_BAD_INSTRUCTIONS at FAKIconImageManager.m Line 49 

SEL selector = NSSelectorFromString([NSString stringWithFormat:@"%@IconWithSize:",[self camelcase:iconIdentifier]]);

My console is logging 
registerForRemoteNotificationTypes: is not supported in iOS 8.0 and later.

It is fine if I debug in phone though

**Comment by admmasters** [comment]
Hi - registerForRemoteNotificationTypes will be related to Push Notifications changes in iOS8 - http://stackoverflow.com/questions/24454033/registerforremotenotificationtypes-is-not-supported-in-ios-8-0-and-later - this should have nothing to do with react-native-icons. Have you got breakpoint exceptions enabled in Xcode?

**Comment by corymsmith** [comment]
Version 0.2.0 with support for the latest RN versions has just been published, should resolve any of those issues, if you still have problems doublecheck that the font you are using is added to the target and being copied.
