### ISSUE TITLE
Upgrade to FontAwesome 4.3

### ISSUE THREAD

**Issue by jacob-israel-turner** [corymsmith/react-native-icons#66]
Hey guys! Great library.  It's been very convenient.

Are there any plans to upgrade to FontAwesome 4.3?  I'm trying to use [venus-mars](http://fortawesome.github.io/Font-Awesome/icon/venus-mars/), and it's not included in the current version.

**Comment by michaelcontento** [comment]
+1

But please skip 4.3 and jump on 4.4 which has been released a few hours ago :sunglasses:

**Comment by jacob-israel-turner** [comment]
If I can be prodded in the right direction, I'd be willing to give a PR a try.  :)

**Comment by corymsmith** [comment]
I just updated to 4.4 and published v0.2.1 to NPM

**Comment by jacob-israel-turner** [comment]
:tada:  You rock!
