### ISSUE TITLE
Inclusion of Material Icons

### ISSUE THREAD

**Issue by piyushchauhan2011** [corymsmith/react-native-icons#67]
#### It would be very useful if we can have material design icons also included.

[Material Design Icons](https://www.google.com/design/icons/)
[Material Icons Guide](https://google.github.io/material-design-icons/)

@corymsmith

**Comment by corymsmith** [comment]
@piyushchauhan2011 I just added Material icons and released v0.3.0 to NPM, thanks for the request!
