### ISSUE TITLE
libReactNativeIcons.a causes project fail

### ISSUE THREAD

**Issue by scottwall0** [corymsmith/react-native-icons#70]
I may be totally doing this wrong, but adding libReactNativeIcons.a to my Link Binary with Libraries Build Phase causes the build to fail. I was wondering if you had any idea why that might be.

**Comment by scottwall0** [comment]
Undefined symbols for architecture x86_64:
  "_RCTRegisterModule", referenced from:
      +[SMXTabBarItemManager load] in libReactNativeIcons.a(SMXTabBarItemManager.o)
      +[SMXTabBarManager load] in libReactNativeIcons.a(SMXTabBarManager.o)
      +[FAKIconImageManager load] in libReactNativeIcons.a(FAKIconImageManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by corymsmith** [comment]
@scottwall0 I'm guessing this has something to do with how everything is being included. Make sure that you've confirmed all the setup steps and you're including React Native Icons in the right project / target.

**Comment by corymsmith** [comment]
Closing this for now as it appears it wasn't added to the project correctly
