### ISSUE TITLE
Material Design Icons works normally but not in TabBar

### ISSUE THREAD

**Issue by mutp** [corymsmith/react-native-icons#72]
This works,
          <Icon name='material|face' size={90} style={{width:90, height: 90}} color='gray' />

but this does not,
      <TabBarItemIOS
          name="settings"
          iconName={'material|face'}
          title={''}
          iconSize={32}
          accessibilityLabel="Settings Tab"
          selected={this.state.selectedTab === 'settings'}
          onPress={() => {
          this.setState({
            selectedTab: 'settings',
          });
        }}>
        {this._renderContent()}
      </TabBarItemIOS>

The error is "No icon font named 'material' ". Great job with repo :)

**Comment by corymsmith** [comment]
Good catch, that's an oversight on my part. It's missing an if statement in SMXTabBarItemManager, if you take a look at the commit for Material icons you'll see that if statement added to FAKIconManager. I can fix tomorrow or if you want to do a PR I can merge it in. Or if you just want to get it up and running on your project until I can fix it properly :)

**Comment by mutp** [comment]
Happy to help :) Sent the PR. Hope its all good!

**Comment by corymsmith** [comment]
It's perfect; I'll push to NPM when I get a chance later today / tomorrow.

Thanks!

**Comment by corymsmith** [comment]
Just merged in and pushed version 0.3.1 to NPM
