### ISSUE TITLE
The icon 'fontawesome|balance-scale' gets cut off

### ISSUE THREAD

**Issue by wheycool** [corymsmith/react-native-icons#78]
The icon 'fontawesome|balance-scale' gets cut off on the horizontal edges, despite increasing the style's width, height, and decreasing the icon's size. I've done this in a blank, full-screen container, and still encounter the issue.

**Comment by corymsmith** [comment]
This is the same issue as #55

**Comment by corymsmith** [comment]
Closing as we'll track this in #55
