### ISSUE TITLE
TabBarIOS.Item - Fixed width/height vs constraints

### ISSUE THREAD

**Issue by owenconti** [corymsmith/react-native-icons#79]
I ran into an annoying issue this afternoon where all of my TabBarIOS.Items were not adjusting to 100% width when in landscape mode. It turns out your version of TabBarIOS.Item's styles is slightly different than the original React Native version.

Your version: https://github.com/corymsmith/react-native-icons/blob/master/SMXTabBarIconItemIOS.ios.js#L88

React Native: https://github.com/facebook/react-native/blob/master/Libraries/Components/TabBarIOS/TabBarItemIOS.ios.js#L136

If I open my app in landscape mode, the dimensions returned via `Dimensions.get('window')` are always that of the portrait orientation. 

Can this be changed to use constraints like the original implementation does?

**Comment by corymsmith** [comment]
@owenconti Just published 0.3.5 that has this change in it
