### ISSUE TITLE
Doesn't seem to install properly (missing file under ReactNativeIcons.xcodeproj)

### ISSUE THREAD

**Issue by pedramsaleh** [corymsmith/react-native-icons#84]
I followed all the installation instructions provided, but after following the step to add the libReacNativeIcons.a file to my project, it shows up as red.  When I look at the path for it, it's looking for a folder that doesn't exist on my system (Users/{username}/Library/Developer/Xcode/DerivedData/{project_name}-dtmkeltphoenbtbjymyjdnwscknc/Build/Products/Debug-iphoneos/libReactNativeIcons.a).  I don't have a "Library" folder under my user folder.  I'm guessing that's why I got a "Invariant Violation: Expected a component class, got [object Object]" error when trying to use the <Icon> component.
I didn't see any error when installing through npm, so I'm not sure what could have gone wrong.  Any idea why the library file would be missing?

**Comment by corymsmith** [comment]
I'm guessing you may have added it to the wrong project or something. Make sure you follow each step, I've seen this error in the past when people had added this library to the ReactNative project instead.

**Comment by pedramsaleh** [comment]
I don't believe I've added it to the wrong project.  You can see in this screenshot that it's in my main project, and that it's highlighted red, and the non-existent path is on the right: http://i62.tinypic.com/2vx1637.jpg

**Comment by corymsmith** [comment]
What version of React Native are you using?

**Comment by pedramsaleh** [comment]
0.8.0

**Comment by corymsmith** [comment]
Can you post the code you're trying to use? If you're getting an invariant violation it may be the way you're using it.

**Comment by pedramsaleh** [comment]
Basically there's only two parts that refer to it.  

At the very top I have (among other declarations) 
var Icon = require('react-native-icons');

Then in the render method I have

```
                      <Icon
                          name='fontawesome|star'
                          size={20}
                          color='#887700'
                          style={styles.nestedText}
                      />
```

If I remove the Icon component, all is fine.  I've also posted the full JS file here (it's just a prototype right now so the code might be a little dirty):  http://pastebin.com/x9kd99JN

**Comment by corymsmith** [comment]
You'll have to change this:

var Icon = require('react-native-icons');

To this:

var Icon = require('react-native-icons').Icon;

If you look at the index.js of this module you'll see the 3 exports.

**Comment by corymsmith** [comment]
Let me know if this works for you :)

**Comment by pedramsaleh** [comment]
That did the trick.  Thanks!  I was going by the example code, which didn't have the ".Icon" at the end of the require statement (which might a bit confusing for others following it too).

**Comment by corymsmith** [comment]
The example code is using the new ES6 import syntax:

var { Icon, TabBarIOS, Spinner} =   require('react-native-icons');

is equivalent to this in regular JavaScript:

var Icon = require('react-native-icons').Icon;

var TabBarIOS = require('react-native-icons').TabBarIOS;

var Spinner = require('react-native-icons').Spinner;

**Comment by pedramsaleh** [comment]
Thanks.  I was just missing the curly braces.   All my other require statements are like that, just without the curly braces.

**Comment by corymsmith** [comment]
Perfect, glad that works!

**Comment by jonolock91** [comment]
Hi, I'm having a similar problem, I had my icons all working with Fontawsome, but then after trying to add the Ion font file to my project it broke. So I uninstalled the Icon node module and re-installed it, but I'm having a problem with my libReactNativeIcons.a file being red, and when I add this file to my link binary with libraries my project fails. I'm using React Native 0.14, any ideas would be helpful please.
