### ISSUE TITLE
0.3.6 breaks RN 0.9.0

### ISSUE THREAD

**Issue by jacob-israel-turner** [corymsmith/react-native-icons#87]
I just barely noticed that you changed the dependency to RN 0.10.0 in https://github.com/corymsmith/react-native-icons/commit/075d113f6e339e092458a17fe326f701b8876365, but I thought I'd still post if it's helpful for anyone else.

I get this error when building.  I am using `react-native-icons@0.3.6` and `react-native@0.9.0`.

<img width="381" alt="screen shot 2015-09-02 at 18 11 32" src="https://cloud.githubusercontent.com/assets/8698364/9638486/ecce4b0e-519e-11e5-9b06-54b8b5f295c1.png">

As a breaking change, this warrants at least a minor, if not a major, version change.

Switching back to 0.3.5 fixes the problem (haven't tried 0.3.6 with RN 0.10.0).

**Comment by cutemachine** [comment]
I had the same issue. Updating RN to 0.10.1 solved it for me.

**Comment by corymsmith** [comment]
I'm away on vacation until the 14th so will do a 0.4.0 for RN 0.11 when its released

**Comment by olitomas** [comment]
Any news on this ? I have RN 0.10.1 and RN-icons 0.3.6 but cant get things working. I have tried downgrading RN to 0.10.0 and also the RN-icons to 0.3.5. 

Only way i get the icons working is with RN at 0.8.0 and RN-icons 0.3.3.

However I need react 0.10.x because of other modules i need for my project.

**Comment by corymsmith** [comment]
@olitomas What issues are you having? 0.3.6 should work with 0.10.1, I'm doing an update today with support for 0.11.0. I will let you know when its published to NPM so you can try it out

**Comment by olitomas** [comment]
The build does not fail on 0.3.6 and 0.10.1 but the icons spots are empty....but no errors though (But they work when i downgrade back to RN 0.8.0 and RN-icons 0.3.3 as stated earlier).

Sounds awesome, thanks so much !

**Comment by corymsmith** [comment]
Just published 0.4.0 to NPM, should fix things.

**Comment by olitomas** [comment]
For anyone with the same problem as me, the following steps fixed it:
1. Build Phases - > Copy Bundle Resources -> '+' -> Add Others -> Select the "FontAwesome.otf" file(node_modules/react-native-icons/ios/ReactNativeIcons/Libraries/FontAwesomeKit/)
2. Clean Project("CMD + SHIFT + K")
3. Build and run.
