### ISSUE TITLE
Icons Not  Showing Up, No Errors

### ISSUE THREAD

**Issue by cjnething** [corymsmith/react-native-icons#88]
Hi, I'm having an issue where my icons aren't showing up. I think I did everything that was on the "getting started" page and all of the suggestions from previous questions with similar problems, but to no avail. There are no errors that I can tell. I'm pretty new to React Native and XCode so I'm not even sure how to debug this. Not sure what would be helpful for you, so I included a few screen shots but please let me know if you need other information from me! Thanks!

<img width="528" alt="screen shot 2015-09-07 at 6 37 23 pm" src="https://cloud.githubusercontent.com/assets/8431037/9724635/ba00259a-558f-11e5-87fe-932bfedd152a.png">
<img width="685" alt="screen shot 2015-09-07 at 6 38 03 pm" src="https://cloud.githubusercontent.com/assets/8431037/9724639/c1691ff8-558f-11e5-81a6-df03c06d33d3.png">
<img width="706" alt="screen shot 2015-09-07 at 6 38 16 pm" src="https://cloud.githubusercontent.com/assets/8431037/9724641/c8da9adc-558f-11e5-9f1a-9a1eeee0ede8.png">

**Comment by corymsmith** [comment]
Do you have a width and height in that lightbulb style? If not you'll have to add them, other then that it looks like you have it all set up correctly :)

**Comment by cjnething** [comment]
Oh my goodness, my apologies! I had that earlier and deleted it for whatever reason. It works now :) Thanks!!

**Comment by corymsmith** [comment]
No worries! I should add something to the Readme about that since it's come up quite a few times

**Comment by kunalnagar** [comment]
Unable to see icon when using TabBarIOS.Item:

React Native: v.0.12.0
React Native Icons: v.0.5.1

```
<TabBarIOS>
	<TabBarIOS.Item
		name="redTab"
  		iconName={'ion|ios-home-outline'}
  		selectedIconName={'ion|ios-home'}
  		iconSize={32}
			title="Scheduled"
			accessibilityLabel="Scheduled"
  		badge={this.state.notifCount > 0 ? this.state.notifCount : undefined}
  		selected={this.state.selectedTab === 'redTab'}
  		onPress={() => {
    		this.setState({
      			selectedTab: 'redTab',
      			notifCount: this.state.notifCount + 1,
    		});
  		}}>
  		{this._renderContent('#783E33', 'Red Tab', this.state.notifCount)}
	</TabBarIOS.Item>
</TabBarIOS>
```

![simulator screen shot 16-oct-2015 11 04 20 pm](https://cloud.githubusercontent.com/assets/2741371/10548720/430b48ae-745a-11e5-8555-45e820b0fe41.png)
