### ISSUE TITLE
No manager class found for view with module name "FAKIconImage"

### ISSUE THREAD

**Issue by PhilippKrone** [corymsmith/react-native-icons#9]
Hello,

after integrating everything in my app, I get the following error in XCODE:

[tid:com.facebook.ReactKit.ShadowQueue][RCTUIManager.m:746] No manager class found for view with module name "FAKIconImage"

Do you know the background of this error?

Regards
Philipp

**Comment by corymsmith** [comment]
Hi Philipp, 

Did you set the User Header Search Paths and make sure its set as Recursive? Also, make sure 'Always Search User Paths' is set to YES. Is React Native installed via npm? Make sure that the path used in User Header Search paths such as $(SRCROOT)/../../react-native/React resolves to the proper directory as well.

**Comment by PhilippKrone** [comment]
Hello,

I was able to solve the issue by setting the "Target Membership" for the main project and the sub project correct.

Thanks!
Philipp

**Comment by corymsmith** [comment]
Hey Philipp, glad you got it working. Can you clarify what you mean by that?

Thanks,

Cory Smith
http://ca.linkedin.com/in/corysmith/
http:/twitter.com/smixx http://twitter.com/smixx

**Comment by PhilippKrone** [comment]
Hi,

sure I can! In the properties of the "Products" of the ReactNativeIcons project, I had to set the following:

Product "libReactNativeIcons.a" 
- "ReactNativeIcons": not checked
- "ReactNativeIconsRessources": checked (required)

Product "ReactNativeIconsRessources"
- "ReactNativeIcons": checked
- "ReactNativeIconsRessources": not checked

Regards
Philipp

**Comment by adriansdev** [comment]
I have the same problem, I can't find the product properties for libReactNativeIcons.a and can't see ReactNativeIconsRessources at all. Can you specify where they are more precisely? Thanks

**Comment by corymsmith** [comment]
@adrian-social-prod I've removed ReactNativeIconsResources so you no longer need to follow that particular step. 

For the .a file: assuming you've already dragged the xcodeproj into your project, you should just have to select the Target for your app, go to Build Phases => Link Binary With Libraries then click the + and you should see something similar to this. If you just select libReactNativeIcons.a and press Add it should add it correctly. 
![screenshot 2015-04-16 17 31 08](https://cloud.githubusercontent.com/assets/7315/7193451/34ce0326-e45e-11e4-95e9-3bb936902c37.png)

**Comment by JonasJonny** [comment]
I had the same issue.
Finally I got it working.
The problem was that I include "libReactNativeIcons.a" into ReactNativeIcons.xcodeproj and not "MAIN project". I think the readme is still a little confusing. I recommend add highlighted information which step is for "main" project settings and which is for ReactNativeIcons project.

**Comment by corymsmith** [comment]
@JonasJonny Ok thanks for the feedback, I think I'll update the readme with some screenshots as well.

**Comment by JonasJonny** [comment]
Good idea.
Even now it is much more intuitive than it was.
Thanks for your work!

**Comment by mohammedhammoud** [comment]
Hi, I have this issue and I can't get it to work: [tid:com.facebook.React.ShadowQueue][RCTUIManager.m:754] No manager class found for view with module name "FAKIconImage"
