### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by ghost** [corymsmith/react-native-icons#92]
Are there any plans to add Android support?

**Comment by corymsmith** [comment]
You bet, was going to dig into that shortly

**Comment by waahai** [comment]
+1 for Android support

**Comment by jbrodriguez** [comment]
+1 ... Nice to know you're working on this

**Comment by corymsmith** [comment]
I haven't started yet so anyone that wants to do a PR is welcome :)

**Comment by zth** [comment]
+1 I'd also be very interested in this! Unfortunately I know too little about the Android part to help.. :(

**Comment by wangscu** [comment]
+10086

**Comment by BerndWessels** [comment]
+1 Icons are really important and it would be great if we could use the same icon module on IOS and Android. Would be a shame if somebody else came up with a icon solution for Android and we would have to maintain 2 icon modules across the both platforms.
And now that RN Android is open sourced I really believe this is urgent, hopefully some Android experts can help you drive this fast.
Thanks for the effort and keep up the great work.

**Comment by bgorkem** [comment]
+1 for the Android Support

**Comment by marcusyip** [comment]
+1 android support :+1:

**Comment by Mokto** [comment]
+1 :+1:

**Comment by sowdri** [comment]
+1

**Comment by joeporpeglia** [comment]
Giving this a try

**Comment by corymsmith** [comment]
@joevp I'm starting into this today as well, will update with progress

**Comment by joeporpeglia** [comment]
@corymsmith it's pretty straight forward. I just have to generate a [glyph character file similar to the FontAwesomeKit](https://github.com/corymsmith/react-native-icons/blob/master/iOS/ReactNativeIcons/Libraries/FontAwesomeKit/FAKFontAwesome.m) and it should be good!

**Comment by akmoulai** [comment]
@corymsmith Good luck, this will be useful to a lot of people, including me! Thanks a lot.

**Comment by marty-wang** [comment]
Thanks to whom is looking into it

**Comment by corymsmith** [comment]
I made quite a bit of progress on this over the weekend. I have icons being loaded from all current icon fonts. I need to sort out quite a few issues around styling and sizing before its ready for primetime though. 

As part of this I've made it extensible so its simple to add your own icon font and use it via the Icon componen. (Android only at the moment).

I'll update everyone as I have more to share!

**Comment by colus001** [comment]
+1 Please!

**Comment by corymsmith** [comment]
I just merged in #101 in and published 0.5.0-rc to npm.

**Comment by dsandor** [comment]
Thanks for the Android support @corymsmith and also thanks for updating the readme.  This is working great for me.

**Comment by Pajn** [comment]
Seems to work fine here too. Thanks!
