### ISSUE TITLE
Use custom font

### ISSUE THREAD

**Issue by olitomas** [corymsmith/react-native-icons#93]
Being able to use a custom font (without having to re-implement it whenever updating react-native-icons) would be really great.

**Comment by corymsmith** [comment]
@olitomas Completely agree, I've just implemented this for Android as I've been adding Android support. Will be doing the same for the iOS module as well.

**Comment by olitomas** [comment]
Great to hear !

**Comment by amiuhle** [comment]
Any plans for the iOS version of this?

**Comment by corymsmith** [comment]
@amiuhle I don't have any time to add this these days, http://github.com/oblador/react-native-vector-icons has this functionality

**Comment by amiuhle** [comment]
@corymsmith Thanks for pointing me to `react-native-vector-icons`!

I would have given this issue a try, but I'm not an iOS developer, so I think I would have been kind of lost...

**Comment by corymsmith** [comment]
Closing this as support for this library is being discontinued, I highly recommend using https://github.com/oblador/react-native-vector-icons instead as its more fully featured, I've added a warning to the Readme about this as well.
