### ISSUE TITLE
unknown has no propType... when updating to version 0.4.0

### ISSUE THREAD

**Issue by olitomas** [corymsmith/react-native-icons#94]
I get this when after updating to version 0.4.0
<img width="364" alt="screen shot 2015-09-17 at 15 59 59" src="https://cloud.githubusercontent.com/assets/6918659/9938575/8775e038-5d55-11e5-8855-78cc704a657d.png">

**Comment by cienijr** [comment]
@olitomas it looks like your SMXTabBarIconItemIOS.ios.js is outdated.

At 0.3.6 (https://github.com/corymsmith/react-native-icons/blob/8ffc8b2676e4dda2ac7f0f93058012264630ccb4/SMXTabBarIconItemIOS.ios.js#L95), it was the call for requireNativeComponent (the one that appears on your stacktrace).

However, at 0.4.0 (https://github.com/corymsmith/react-native-icons/blob/8e32b8a0869dc00fda4b3393ae78e7ae2b283598/SMXTabBarIconItemIOS.ios.js#L95), this is merely a style definition.

I'd suggest to run `npm update` and see if it gets the right files. It worked for me :grin:

**Comment by akishek22** [comment]
@cieni I seem to have the 0.4.0 updated file, but my react-debugger is referencing line 97 for some reason.

**Comment by corymsmith** [comment]
@olitomas Did you get this working?

**Comment by olitomas** [comment]
Nope, we went back to 3.4 to get things working :) (npm update or other similar things did not work either)

**Comment by jose-cieni-movile** [comment]
@akishek22 well, that's awkward... can you check for SMXTabBarIconItemIOS.ios.js at line 95 on your node_modules folder and paste it here?

**Comment by cienijr** [comment]
@akishek22 well, that's awkward... can you check for SMXTabBarIconItemIOS.ios.js at line 95 on your node_modules folder and paste it here?
