### ISSUE TITLE
Can't find icon

### ISSUE THREAD

**Issue by pedramsaleh** [corymsmith/react-native-icons#95]
I'm trying to include an icon from the material set, but it gives an error that it can't find it. I check on the web site that has all the icons by name(https://www.google.com/design/icons/), and the name seems right (looks one), but I get an error saying "No icon 'looks one' in 'material' icon font".  I also tried "looks_one" but that didn't work either.  Is there a way I can browse the icons by name to make sure to use the correct name?

Thanks.

**Comment by corymsmith** [comment]
That icon must not have been in the icon set when I generated the code for the icons. I may have to look at a better way to do that

**Comment by pedramsaleh** [comment]
OK no prob.  I used another icon to get what I want, so I can close this if you like.

**Comment by pedramsaleh** [comment]
I got around this by using a different method and was thinking of closing this issue.  Has this been addressed in a newer version?

**Comment by corymsmith** [comment]
@pedramsaleh No the icons have not been fully updated

**Comment by zavoloklom** [comment]
@pedramsaleh, @corymsmith, 
Name of this icon in MDIF is `n-1-square`, you can find it in [Numbers Section](http://zavoloklom.github.io/material-design-iconic-font/icons.html#numbers)
