### ISSUE TITLE
Getting Started needs to be updated for RN 0.11

### ISSUE THREAD

**Issue by tnguyen42** [corymsmith/react-native-icons#97]
Hi, this part particularly isn't up to date anymore:

Add libReactNativeIcons.a (from 'Products' under ReactNativeIcons.xcodeproj) to your project's Build Phases ➜ Link Binary With Libraries phase

And I can't find where to link the binary now by the way ^^
I had too much trouble finding how to fix my packages with the new 0.11 so I decided to start over and here's the first problem...
If anyone's working on 0.11... :-)

Cheers!

**Comment by arunshan** [comment]
I have the same issue with react-native 0.11. I am no longer able to use react-native-icons in my project. I added the dependencies according to the README.

![image 2015-09-22 at 11 54 48 am](https://cloud.githubusercontent.com/assets/1124102/10028357/ce3716c6-6120-11e5-8b68-2c1bf62290c3.png)

**Comment by corymsmith** [comment]
@arunshan Can you share how you are referencing it in your code? And what version of react-native-icons you are using?

**Comment by arunshan** [comment]
I am using the following in package.json

```
    "react-native": "^0.11.0",
    "react-native-icons": "^0.4.0",
```

To reference it, I use the following

```
var {Icon, } = ('react-native-icons');
<Icon
      name='ion|ios-arrow-right'
      size={30}
      color='#777'
      style={styles.lightbulb}
/>
```

**Comment by bmcmahen** [comment]
For what it's worth, I followed the 'Getting Started' guide as-is with RN 0.11 and haven't had any problems.

**Comment by arunshan** [comment]
@corymsmith @bmcmahen My app was working fine before with the following version

```
 "react-native": "^0.4.4",
    "react-native-icons": "0.0.8",
```

I updated my OS to iOS 9 and also updated react native to the latest version. Then I get the issue mentioned above with react-native-icons.

Am I missing something ?

**Comment by maraujop** [comment]
I'm trying react-native-icons version 0.5.0-rc with react-native 0.12.0-rc and Android emulator and I'm getting this screen:

![captura de pantalla 2015-09-29 a las 14 20 16](https://cloud.githubusercontent.com/assets/252257/10163758/552adce6-66b5-11e5-860d-438b94b6a31d.png)

It's like if it is not detecting `Icon` as a component.

Cheers,
Miguel

**Comment by radford-for-smpte** [comment]
So does libReactNativeIcons.a need to be added now to "Link Binary With Libraries" now w/ > 0.11?

With it included, I get:

> node_modules/react-native-icons/ios/ReactNativeIcons/IconTabBarItem/SMXTabBar.m:88:55: No visible @interface for 'RCTWrapperViewController' declares the selector 'initWithContentView:'

**Comment by corymsmith** [comment]
You'll have to use 0.4.0 with React Native 0.11.x

**Comment by corymsmith** [comment]
Is this still an issue? If not let me me know so I can close this.
