### ISSUE TITLE
Issues when uploading to ITunes Connect

### ISSUE THREAD

**Issue by Mokto** [corymsmith/react-native-icons#98]
Hi,

I'm having issues when submitting my app to iTunes Connect :

``` javascript
Invalid Bundle Structure - The binary file 'Songpeek.app/FAKIcon.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.

Invalid Bundle Structure - The binary file 'Songpeek.app/FAKMaterial.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.

Invalid Bundle Structure - The binary file 'Songpeek.app/FAKZocial.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.
```

Is there something I did wrong ?

**Comment by corymsmith** [comment]
Can you share a screenshot of your copy bundle resources phase? 

I've had a similar issue using the Google Plus SDK, here's a SO article about similar errors: http://stackoverflow.com/questions/20251252/invalid-bundle-structure-the-app-may-contain-only-one-executable-file

**Comment by Mokto** [comment]
Thanks ! :+1: 

I have looked your link but I don't think I did something wrong.

![capture d ecran 2015-09-25 a 14 33 28](https://cloud.githubusercontent.com/assets/5103928/10109039/7a2798fc-6392-11e5-91fe-e28ac94f6ace.png)

**Comment by corymsmith** [comment]
@Mokto You should remove all of the .h and .m files from Copy Bundle Resources as they shouldn't be there, that should fix the issue.

**Comment by Mokto** [comment]
Ok thanks a lot.

Sorry for the inconvenience !
